using System;using System.IO;using System.Linq;using PandaLauncher;
class RegressionV10 {
 static int n;static void Check(bool ok,string label){if(!ok)throw new Exception(label);Console.WriteLine("OK : "+label);n++;}
 [STAThread]static void Main(string[] args){string root=args[0],desk=Path.Combine(root,"Bureau"),exe=Path.Combine(root,"Panda Launcher.exe");var store=new CatalogStore(Path.Combine(root,"config.json"));var c=new Catalog();var g=c.Add("Initial");store.Save(c);GroupLinks.SavePreferences(store,c,g,"Initial","violet",true,"Fermer Initial",exe,desk,root,true);string run=Path.Combine(desk,"Initial.lnk"),stop=Path.Combine(desk,"Fermer Initial.lnk");byte[] original=File.ReadAllBytes(run),closeOriginal=File.ReadAllBytes(stop);bool failed=false;
 using(var locked=new FileStream(stop,FileMode.Open,FileAccess.Read,FileShare.Read)){try{GroupLinks.SavePreferences(store,c,g,"Nouveau","dore",true,"Fermer Nouveau",exe,desk,root,true);}catch(IOException){failed=true;}Check(failed,"verrouillage signalé");Check(g.Name=="Initial","modèle restauré malgré le verrouillage");Check(File.Exists(run)&&File.ReadAllBytes(run).SequenceEqual(original),"lancement restauré");Check(!File.Exists(Path.Combine(desk,"Nouveau.lnk"))&&!File.Exists(Path.Combine(desk,"Fermer Nouveau.lnk")),"aucun raccourci partiel après échec");}
 Check(File.ReadAllBytes(stop).SequenceEqual(closeOriginal),"fermeture verrouillée préservée");
 var reader=new CatalogStore(store.PathName);var stale=reader.Read();var other=new CatalogStore(store.PathName);var fresh=other.Read();fresh.Selected.Name=fresh.Selected.ShortcutName="Externe";other.Save(fresh);failed=false;try{reader.Save(stale);}catch(IOException){failed=true;}Check(failed&&new CatalogStore(store.PathName).Read().Selected.Name=="Externe","modification externe non écrasée");
 var bad=new Catalog();var b=bad.Add("Valide");b.ShortcutName=new string('x',101);failed=false;try{CatalogStore.Validate(bad);}catch(IOException){failed=true;}Check(failed,"nom migré invalide refusé");
 string id=Guid.NewGuid().ToString();failed=false;try{Program.GroupArgument(new[]{"--group",id,"--group",Guid.NewGuid().ToString()});}catch(IOException){failed=true;}Check(failed,"identifiants contradictoires refusés");
 c=store.Read();g=c.Selected;var second=c.Add("Autre");store.Save(c);failed=false;using(var locked=new FileStream(stop,FileMode.Open,FileAccess.Read,FileShare.Read)){try{GroupLinks.Delete(store,c,g,desk);}catch(IOException){failed=true;}Check(failed&&c.Groups.Contains(g)&&File.Exists(run)&&File.Exists(stop),"suppression verrouillée restaurée");}
 string impossible=Path.Combine(root,"dossier-config");Directory.CreateDirectory(impossible);failed=false;try{GroupLinks.Delete(new CatalogStore(impossible),c,g,desk);}catch(IOException){failed=true;}Check(failed&&c.Groups.Contains(g)&&File.Exists(run)&&File.Exists(stop),"suppression annulée si sauvegarde échoue");GroupLinks.Delete(store,c,g,desk);Check(!File.Exists(run)&&!File.Exists(stop)&&store.Read().Groups.Count==1,"suppression complète après déverrouillage");failed=false;try{GroupLinks.Delete(store,c,second,desk);}catch(IOException){failed=true;}Check(failed,"dernier launcher protégé");
 var dup=new Catalog();var a=dup.Add("A");var z=dup.Add("Z");z.Id=a.Id.ToUpperInvariant();failed=false;try{CatalogStore.Validate(dup);}catch(IOException){failed=true;}Check(failed,"GUID dupliqué avec casse différente refusé");
 failed=false;try{Program.GroupArgument(new[]{"--launch","--close","--group",id});}catch(IOException){failed=true;}Check(failed,"lancement et fermeture simultanés refusés");
 var entry=new Entry{Name="OBS témoin"};bool asked=false,requested=false;failed=false;try{AppCloser.WithElevationConsent(entry,e=>{asked=e==entry;return false;},()=>{requested=true;return System.Threading.Tasks.Task.FromResult(true);}).GetAwaiter().GetResult();}catch(OperationCanceledException){failed=true;}Check(failed&&asked&&!requested,"annuler avant UAC ne déclenche aucune élévation");
 asked=requested=false;Check(AppCloser.WithElevationConsent(entry,e=>{asked=true;return true;},()=>{Check(asked,"explication précède la demande Windows");requested=true;return System.Threading.Tasks.Task.FromResult(true);}).GetAwaiter().GetResult()&&requested,"OK autorise la demande Windows");
 requested=false;failed=false;try{AppCloser.WithElevationConsent(entry,null,()=>{requested=true;return System.Threading.Tasks.Task.FromResult(true);}).GetAwaiter().GetResult();}catch(OperationCanceledException){failed=true;}Check(failed&&!requested,"aucune élévation sans confirmation disponible");
 Console.WriteLine(n+" contrôles v10 réussis.");}
}


