using System;using System.IO;using System.Linq;using System.Drawing;using System.Windows.Forms;using System.Reflection;using System.Diagnostics;using PandaLauncher;
class RegressionV4 {
 static int count;static void Check(bool ok,string label){if(!ok)throw new Exception(label);Console.WriteLine("OK : "+label);count++;}
 static void Reject(Action action,string label){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,label);}
 [STAThread]static void Main(string[] args){Application.EnableVisualStyles();string root=Path.GetFullPath(args[0]),exe=Path.GetFullPath(args[1]),probe=Path.Combine(root,"Probe.exe"),legacy=Path.Combine(root,"legacy.json"),current=Path.Combine(root,"catalog.json"),desktop=Path.Combine(root,"Bureau été"),icons=Path.Combine(root,"data");Directory.CreateDirectory(desktop);
  var old=new Configuration();old.Entries.Add(new Entry{Name="Témoin",Target=probe,Arguments="\""+Path.Combine(root,"premier.txt")+"\"",SkipRunning=false});new Store(legacy).Save(old);var oldBytes=File.ReadAllBytes(legacy);var store=new CatalogStore(current,legacy);var catalog=store.Read();var first=catalog.Selected;
  Check(catalog.Groups.Count==1&&first.Entries.Single().Id==old.Entries[0].Id,"migration conserve la liste et les identifiants");store.Save(catalog);catalog=store.Read();first=catalog.Selected;Check(oldBytes.SequenceEqual(File.ReadAllBytes(legacy)),"ancienne configuration préservée");Check(catalog.ForLaunch(null).Id==first.Id,"ancien mode sans groupe lié au groupe migré");
  var second=catalog.Add("Quotidien");second.Entries.Add(new Entry{Name="Témoin bis",Target=probe,Arguments="\""+Path.Combine(root,"second.txt")+"\"",SkipRunning=false});store.Save(catalog);Check(store.Read().Groups.Count==2&&store.Read().SelectedId==second.Id,"deux groupes et onglet actif persistés");
  var link1=GroupLinks.Update(first,"Création","turquoise",exe,desktop,icons);var link2=GroupLinks.Update(second,"Quotidien","violet",exe,desktop,icons);store.Save(catalog);Check(GroupLinks.Belongs(link1,first.Id)&&!GroupLinks.Belongs(link1,second.Id),"raccourcis associés par identifiant distinct");var otherBytes=File.ReadAllBytes(link2);
  string manual=Path.Combine(desktop,"Nom changé à la main.lnk");File.Move(link1,manual);Check(GroupLinks.Find(first,desktop)==manual,"raccourci renommé manuellement retrouvé");first.Name="Création renommée";var renamed=GroupLinks.Update(first,"Mon nouveau nom","fuchsia",exe,desktop,icons);store.Save(catalog);Check(!File.Exists(manual)&&GroupLinks.Belongs(renamed,first.Id),"renommage et icône mis à jour sans nouveau doublon");Check(otherBytes.SequenceEqual(File.ReadAllBytes(link2)),"autre groupe et raccourci inchangés");
  Reject(()=>GroupLinks.Update(first,"Quotidien","dore",exe,desktop,icons),"collision avec un autre groupe refusée");Check(otherBytes.SequenceEqual(File.ReadAllBytes(link2)),"collision ne modifie aucun raccourci tiers");
  string copy=Path.Combine(desktop,"Copie.lnk");File.Copy(renamed,copy);Reject(()=>GroupLinks.Find(first,desktop),"copies ambiguës signalées");File.Delete(copy);
  foreach(string color in GroupLinks.Colors){string icon=GroupLinks.ExportIcon(color,icons);using(var i=new Icon(icon))Check(i.Width>0,"icône embarquée "+color);}
  foreach(string name in new[]{"CON","abc/def","nom.","","LPT1.txt"})Reject(()=>GroupLinks.ValidateName(name),"nom invalide refusé : "+name);
  first.Entries[0].Name="Modifié";store.Save(catalog);var selected=store.Read().ForLaunch(first.Id);Check(selected.Entries[0].Name=="Modifié"&&selected.Id!=store.Read().Selected.Id,"raccourci relit son groupe même si autre onglet actif");
  Check(Launcher.Run(selected,(e,s,f)=>{}).GetAwaiter().GetResult()==0,"lancement isolé du premier groupe");for(int i=0;i<100&&!File.Exists(Path.Combine(root,"premier.txt"));i++)System.Threading.Thread.Sleep(30);Check(File.Exists(Path.Combine(root,"premier.txt"))&&!File.Exists(Path.Combine(root,"second.txt")),"aucun programme du second groupe lancé");
  Check(Program.GroupArgument(new[]{"--launch","--group",second.Id})==second.Id,"argument du raccourci résolu");Reject(()=>Program.GroupArgument(new[]{"--launch","--group"}),"argument de groupe incomplet refusé");Reject(()=>catalog.ForLaunch(Guid.NewGuid().ToString()),"groupe supprimé ou inconnu refusé sans repli");
  while(catalog.Groups.Count<5)catalog.Add("Groupe "+catalog.Groups.Count);store.Save(catalog);Reject(()=>catalog.Add("Sixième"),"limite de cinq groupes");Check(store.Read().Groups.Count==5,"cinq groupes restaurés après lecture");
  using(var f=new MainForm(store)){f.Show();Application.DoEvents();var tabField=typeof(MainForm).GetField("tabs",BindingFlags.Instance|BindingFlags.NonPublic);var tabs=(FlowLayoutPanel)tabField.GetValue(f);Check(tabs.Controls.Count==5,"cinq onglets affichés");((Button)tabs.Controls[0]).PerformClick();Check(store.Read().SelectedId==first.Id,"changement d’onglet enregistré");f.Close();}
  GroupLinks.Remove(second,desktop);catalog.Groups.Remove(second);catalog.SelectedId=first.Id;store.Save(catalog);Check(!File.Exists(link2)&&File.Exists(renamed),"suppression ciblée du raccourci d’un groupe");Reject(()=>store.Read().ForLaunch(second.Id),"ancien raccourci du groupe supprimé ne lance rien");
  File.WriteAllText(current,"{corrompu");Reject(()=>store.Read(),"JSON corrompu refusé");Check(File.ReadAllText(current)=="{corrompu","JSON corrompu conservé");Console.WriteLine(count+" vérifications v4 réussies.");
 }
}
