using System;using System.IO;using System.Linq;using System.Diagnostics;using System.Threading;using System.Windows.Forms;using System.Reflection;using System.Drawing;using PandaLauncher;
class RegressionV6 {
 static int count;static void Check(bool ok,string label){if(!ok)throw new Exception(label);Console.WriteLine("OK : "+label);count++;}
 static object Field(object o,string name){return o.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}
 static object Call(object o,string name,params object[] args){return o.GetType().GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,args);}
 static void AwaitFile(string p){for(int i=0;i<100&&!File.Exists(p);i++)Thread.Sleep(30);Check(File.Exists(p),"fenêtre témoin créée");}
 [STAThread]static void Main(string[] args){string root=Path.GetFullPath(args[0]),helper=Path.Combine(root,"SlowWindow.exe"),otherFolder=Path.Combine(root,"autre");Directory.CreateDirectory(otherFolder);string other=Path.Combine(otherFolder,"SlowWindow.exe");File.Copy(helper,other,true);
 var c=new Configuration();var target=new Entry{Name="Cible décochée",Target=helper,Enabled=false};c.Entries.Add(target);var states=new System.Collections.Generic.List<string>();string proof=Path.Combine(root,"cible.txt"),otherProof=Path.Combine(root,"autre.txt");using(var p=Process.Start(helper,"\""+proof+"\" 0 4500"))using(var q=Process.Start(other,"\""+otherProof+"\" 0 4500")){AwaitFile(proof);AwaitFile(otherProof);Check(AppCloser.Close(c,(e,s,error)=>{states.Add(s);Console.WriteLine(s);}).GetAwaiter().GetResult()==0,"fermeture normale du programme du groupe");Check(p.WaitForExit(1000),"processus ciblé fermé");Check(!q.HasExited,"homonyme hors du groupe laissé ouvert");Check(states.Last()=="Application fermée","fermeture confirmée après disparition");q.WaitForExit(6000);}
 states.Clear();Check(AppCloser.Close(c,(e,s,error)=>{states.Add(s);Console.WriteLine(s);}).GetAwaiter().GetResult()==0&&states.Single()=="Déjà fermé","application déjà fermée ignorée");
 string refusalProof=Path.Combine(root,"refus.txt");using(var refusing=Process.Start(helper,"\""+refusalProof+"\" 0 3800 refuse")){AwaitFile(refusalProof);Check(AppCloser.Close(c,(e,s,error)=>{},null,2500).GetAwaiter().GetResult()==1,"refus de fermeture signalé");Check(!refusing.HasExited,"aucune fermeture forcée après refus");refusing.WaitForExit(5000);}
 string script=Path.Combine(root,"script été.cmd"),bad=Path.Combine(root,"document.txt");File.WriteAllText(script,"@echo off");File.WriteAllText(bad,"test");var sc=new Configuration();sc.Entries.Add(new Entry{Name="Script",Target=script});Check(AppCloser.Close(sc,(e,s,error)=>{}).GetAwaiter().GetResult()==1,"script non identifiable non fermé arbitrairement");
 var batch=DropBatch.Prepare(new[]{helper,helper,script,bad,root},new Entry[0]);Check(batch.Added.Count==2&&batch.Issues.Count==3,"dépôt multiple : doublons et formats filtrés");Check(batch.Added[1].WorkingDirectory==root&&batch.Added[1].Name=="script été","nom et dossier préremplis");Check(DropBatch.Prepare(new[]{helper},new[]{target}).Added.Count==0,"doublon désactivé déjà dans le groupe exclu");
 Application.EnableVisualStyles();var store=new CatalogStore(Path.Combine(root,"config.json"));var catalog=new Catalog();catalog.Add("Dépôt");store.Save(catalog);using(var f=new MainForm(store)){f.Show();Application.DoEvents();var data=new DataObject();data.SetData(DataFormats.FileDrop,new[]{helper,script,bad});var evt=new DragEventArgs(data,0,0,0,DragDropEffects.Copy,DragDropEffects.None);Check((bool)Call(f,"ValidFiles",evt),"dépôt Windows accepté par la fenêtre");using(var timer=new System.Windows.Forms.Timer{Interval=80}){timer.Tick+=(s,e)=>{foreach(Form dialog in Application.OpenForms.Cast<Form>().ToArray())if(dialog.Text=="Ajouter les programmes déposés"){var actions=dialog.Controls.OfType<FlowLayoutPanel>().Single();actions.Controls.OfType<Button>().First().PerformClick();timer.Stop();}};timer.Start();Call(f,"HandleDrop",Field(f,"grid"),evt);}Check(store.Read().Selected.Entries.Count==2,"validation du dépôt ajoute et sauvegarde les fichiers");using(var timer=new System.Windows.Forms.Timer{Interval=80}){timer.Tick+=(s,e)=>{foreach(Form dialog in Application.OpenForms.Cast<Form>().ToArray())if(dialog.Text=="Ajouter les programmes déposés"){dialog.DialogResult=DialogResult.Cancel;timer.Stop();}};timer.Start();Call(f,"HandleDrop",Field(f,"grid"),evt);}Check(store.Read().Selected.Entries.Count==2,"annulation ne modifie pas la liste");f.Close();}
 Console.WriteLine(count+" vérifications v6 réussies.");}
}

