using System;using System.IO;using System.Diagnostics;using System.Threading;using PandaLauncher;
class RegressionV7 {
 static int n;static void Check(bool b,string s){if(!b)throw new Exception(s);Console.WriteLine("OK : "+s);n++;}
 static Process Start(string exe,string root,string mode){string proof=Path.Combine(root,Guid.NewGuid()+".txt");var p=Process.Start(exe,"\""+proof+"\" 0 20000 "+mode);for(int i=0;i<100&&!File.Exists(proof);i++)Thread.Sleep(30);if(!File.Exists(proof))throw new Exception("Témoin absent");return p;}
 [STAThread]static void Main(string[] a){string root=a[0],exe=Path.Combine(root,"SlowWindow.exe");var c=new Configuration();var e=new Entry{Name="Témoin",Target=exe};c.Entries.Add(e);
 using(var p=Start(exe,root,"hidden")){Check(RuntimeProbe.Read(e).Kind==RuntimeKind.Running,"fenêtre cachée détectée active");Check(AppCloser.Close(c,(x,s,b)=>{},null,1000).GetAwaiter().GetResult()==0,"fermeture normale fenêtre cachée");Check(p.WaitForExit(1000),"disparition confirmée");}
 using(var p=Start(exe,root,"headless")){try{Check(RuntimeProbe.Read(e).Kind==RuntimeKind.Running,"processus sans fenêtre détecté");Check(AppCloser.Close(c,(x,s,b)=>{},x=>false,100).GetAwaiter().GetResult()==1&&!p.HasExited,"refus de forcer respecté");bool rejected=false;try{AppCloser.ActOnProcess(p.Id,p.StartTime.ToUniversalTime().Ticks+1,exe,true);}catch(IOException){rejected=true;}Check(rejected&&!p.HasExited,"PID avec date différente refusé");rejected=false;try{AppCloser.ActOnProcess(p.Id,p.StartTime.ToUniversalTime().Ticks,exe+"x",true);}catch(IOException){rejected=true;}Check(rejected&&!p.HasExited,"chemin différent refusé");Check(AppCloser.Close(c,(x,s,b)=>{},x=>true,100).GetAwaiter().GetResult()==0,"processus sans fenêtre fermé après accord");Check(RuntimeProbe.Read(e).Kind==RuntimeKind.Stopped,"état arrêté confirmé");}finally{if(!p.HasExited)p.Kill();}}
 var g=new Group{Name="Groupe test",ShortcutName="Test"};string desktop=Path.Combine(root,"Bureau");string link=GroupLinks.CreateClose(g,Path.Combine(root,"Panda Launcher.exe"),desktop,root);Check(GroupLinks.IsCloseLink(link,g.Id),"raccourci fermeture associé au GUID");Check(!GroupLinks.Belongs(link,g.Id),"raccourci fermeture distinct du lancement");string renamed=Path.Combine(desktop,"Renommé.lnk");File.Move(link,renamed);Check(GroupLinks.CreateClose(g,exe,desktop,root)==renamed,"raccourci renommé retrouvé sans doublon");Check(!GroupLinks.IsCloseLink(renamed,Guid.NewGuid().ToString()),"autre groupe exclu");GroupLinks.Remove(g,desktop);Check(!File.Exists(renamed),"suppression nettoie le raccourci fermeture");Console.WriteLine(n+" contrôles v7 réussis.");}
}
