using System;using System.IO;using System.Linq;using System.Drawing;using System.Windows.Forms;using System.Reflection;using System.Diagnostics;using System.Threading;using PandaLauncher;
class RegressionV5 {
 static int count;static void Check(bool ok,string label){if(!ok)throw new Exception(label);Console.WriteLine("OK : "+label);count++;}
 static object Field(object o,string name){return o.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}
 static object Call(object o,string name,params object[] args){return o.GetType().GetMethod(name,BindingFlags.NonPublic|BindingFlags.Instance).Invoke(o,args);}
 static void PumpUntil(Func<bool> predicate,int timeout){var time=Stopwatch.StartNew();while(!predicate()&&time.ElapsedMilliseconds<timeout){Application.DoEvents();Thread.Sleep(30);}Check(predicate(),"résultat asynchrone avant "+timeout+" ms");}
 static void Reject(Action action,string label){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,label);}
 [STAThread]static void Main(string[] args){string root=Path.GetFullPath(args[0]),exe=Path.GetFullPath(args[1]),desktop=Path.Combine(root,"Bureau"),iconRoot=Path.Combine(root,"data"),probe=Path.Combine(root,"Probe.exe"),slow=Path.Combine(root,"SlowWindow.exe");Directory.CreateDirectory(desktop);
  var c=new Catalog();var g=c.Add("Premier");g.ShortcutName="Premier";var second=c.Add("Second");c.SelectedId=g.Id;var store=new CatalogStore(Path.Combine(root,"config.json"));store.Save(c);
  string old=GroupLinks.Update(g,"Premier","turquoise",exe,desktop,iconRoot);string other=GroupLinks.Update(second,"Second","violet",exe,desktop,iconRoot);var untouched=File.ReadAllBytes(other);
  g.ShortcutName="Nom prévu";GroupLinks.SynchronizeExternalName(g,old);Check(g.ShortcutName=="Nom prévu","préférence non écrasée par le nom actuel du fichier");
  string updated=GroupLinks.Update(g,g.ShortcutName,"dore",exe,desktop,iconRoot);Check(!File.Exists(old)&&File.Exists(updated),"ancien fichier renommé réellement");updated=GroupLinks.Update(g,"NOM PRÉVU","fuchsia",exe,desktop,iconRoot);Check(Path.GetFileName(GroupLinks.Find(g,desktop))=="NOM PRÉVU.lnk","renommage limité à la casse confirmé");Check(untouched.SequenceEqual(File.ReadAllBytes(other)),"autre raccourci intact");
  var manual=Path.Combine(desktop,"Nom externe.lnk");File.Move(updated,manual);Check(GroupLinks.SynchronizeExternalName(g,manual)&&g.ShortcutName=="Nom externe","renommage externe adopté sans modification en attente");store.Save(c);
  string windowProof=Path.Combine(root,"fenetre.txt"),nextProof=Path.Combine(root,"suivant.txt");var chain=new Configuration();var prerequisite=new Entry{Name="Fenêtre lente",Target=slow,Arguments="\""+windowProof+"\" 900 2000",WaitMode=2,WaitTimeoutSeconds=5};chain.Entries.Add(prerequisite);chain.Entries.Add(new Entry{Name="Suivant",Target=probe,Arguments="\""+nextProof+"\"",Position=1});var messages=new System.Collections.Generic.List<string>();var watch=Stopwatch.StartNew();Check(Launcher.Run(chain,(e,s,f)=>messages.Add(s)).GetAwaiter().GetResult()==0,"séquence avec fenêtre réactive réussie");Check(watch.ElapsedMilliseconds>=900&&messages.Any(s=>s.Contains("fenêtre réactive détectée")),"confirmation attend réellement la fenêtre");for(int i=0;i<80&&!File.Exists(nextProof);i++)Thread.Sleep(30);Check(File.Exists(windowProof)&&File.Exists(nextProof)&&File.GetLastWriteTimeUtc(nextProof)>=File.GetLastWriteTimeUtc(windowProof),"suivant lancé après la fenêtre du prérequis");
  foreach(var p in Process.GetProcessesByName("SlowWindow"))using(p)p.WaitForExit(5000);
  var timeoutConfig=new Configuration();timeoutConfig.Entries.Add(new Entry{Name="Sans fenêtre",Target=slow,Arguments="\""+Path.Combine(root,"absent.txt")+"\" 0 1800 headless",WaitMode=2,WaitTimeoutSeconds=1});string forbidden=Path.Combine(root,"ne-doit-pas-exister.txt");timeoutConfig.Entries.Add(new Entry{Name="Dépendant",Target=probe,Arguments="\""+forbidden+"\"",Position=1});messages.Clear();Check(Launcher.Run(timeoutConfig,(e,s,f)=>messages.Add(s)).GetAwaiter().GetResult()==1,"expiration de l’attente signalée");Check(!File.Exists(forbidden)&&messages.Any(s=>s.Contains("Non lancé")),"suite bloquée lorsque le prérequis ne devient pas réactif");
  foreach(var p in Process.GetProcessesByName("SlowWindow"))using(p)p.WaitForExit(5000);
  string aliveFile=Path.Combine(root,"alive.txt");using(var process=Process.Start(new ProcessStartInfo(probe,"\""+aliveFile+"\" wait"){UseShellExecute=false,CreateNoWindow=true})){var entry=new Entry{Name="Témoin",Target=probe,WaitMode=1,WaitTimeoutSeconds=1};Check(Launcher.WaitForReady(Shortcuts.Resolve(entry),1,1,s=>{}).GetAwaiter().GetResult(),"attente du processus déjà ouvert immédiate");Check(RuntimeProbe.Read(entry).Kind==RuntimeKind.Running,"état détecté même si lancé hors du launcher");process.WaitForExit();Check(RuntimeProbe.Read(entry).Kind==RuntimeKind.Stopped,"arrêt du processus détecté");}
  string script=Path.Combine(root,"test.cmd");File.WriteAllText(script,"@echo off");var scriptEntry=new Entry{Name="Script",Target=script};Check(RuntimeProbe.Read(scriptEntry).Kind==RuntimeKind.Unsupported,"script non présenté comme un logiciel détecté");Reject(()=>Launcher.WaitForReady(Shortcuts.Resolve(scriptEntry),1,1,s=>{}).GetAwaiter().GetResult(),"attente impossible d’un script refusée");Check(RuntimeProbe.Read(new Entry{Name="Absent",Target=Path.Combine(root,"absent.exe")}).Kind==RuntimeKind.Error,"cible manquante explicite");
  Application.EnableVisualStyles();g.Entries.Add(new Entry{Name="Externe",Target=probe});second.Entries.Add(new Entry{Name="Même programme",Target=probe});c.SelectedId=g.Id;store.Save(c);
  using(var f=new MainForm(store,null,desktop,iconRoot)){f.Show();Application.DoEvents();var button=(Button)Field(f,"shortcutButton");Check(button.Text=="Mettre à jour le raccourci","bouton existant affiche la mise à jour");var loaded=(Catalog)Field(f,"catalog");var active=(Group)Field(f,"config");GroupLinks.SavePreferences(store,loaded,active,"Nouveau via bouton","emeraude",false,"Fermer Nouveau",exe,desktop,iconRoot);Check(File.Exists(manual)&&!File.Exists(Path.Combine(desktop,"Nouveau via bouton.lnk")),"paramètres seuls enregistrent sans modifier le Bureau");button.PerformClick();Check(File.Exists(Path.Combine(desktop,"Nouveau via bouton.lnk"))&&!File.Exists(manual),"bouton direct applique le nom sans seconde fenêtre");Check(Application.OpenForms.Count==1,"aucune page de paramètres redondante");
   GroupLinks.Remove(active,desktop);Call(f,"RefreshShortcutButton");Check(button.Text=="Créer le raccourci","bouton détecte un raccourci supprimé");button.PerformClick();Check(File.Exists(Path.Combine(desktop,"Nouveau via bouton.lnk")),"création directe depuis les préférences");
   using(var p=Process.Start(new ProcessStartInfo(probe,"\""+Path.Combine(root,"live.txt")+"\" wait"){UseShellExecute=false,CreateNoWindow=true})){var grid=(DataGridView)Field(f,"grid");PumpUntil(()=>Convert.ToString(grid.Rows[0].Cells[3].Value).Contains("Logiciel lancé"),2500);Check(true,"interface détecte un démarrage extérieur");var tabs=(FlowLayoutPanel)Field(f,"tabs");((Button)tabs.Controls[1]).PerformClick();PumpUntil(()=>Convert.ToString(grid.Rows[0].Cells[3].Value).Contains("Logiciel lancé"),2000);Check(true,"état actualisé dans un autre onglet");PumpUntil(()=>p.HasExited,5000);PumpUntil(()=>Convert.ToString(grid.Rows[0].Cells[3].Value).Contains("Non ouvert"),3000);Check(true,"interface actualise la fermeture extérieure");}
   f.Close();
  }
  var saved=store.Read();Check(saved.Groups[0].ShortcutName=="Nouveau via bouton","préférences conservées après fermeture");Console.WriteLine(count+" vérifications v5 réussies.");
 }
}

