using System;using System.IO;using System.Linq;using System.Drawing;using System.Reflection;using System.Windows.Forms;using PandaLauncher;
class RegressionV9 {
 static int count;static void Check(bool b,string s){if(!b)throw new Exception(s);Console.WriteLine("OK : "+s);count++;}
 static T Field<T>(object o,string n){return (T)o.GetType().GetField(n,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(o);}
 static void Call(object o,string n){o.GetType().GetMethod(n,BindingFlags.Instance|BindingFlags.NonPublic).Invoke(o,null);}
 [STAThread]static void Main(string[] args){Application.EnableVisualStyles();string root=args[0],desk=Path.Combine(root,"Bureau-test"),exe=Path.Combine(root,"Panda Launcher.exe");var store=new CatalogStore(Path.Combine(root,"config.json"));var c=new Catalog();var g=c.Add("Stream");store.Save(c);
 Action<string,bool,string,bool> save=(name,on,close,apply)=>GroupLinks.SavePreferences(store,c,g,name,"violet",on,close,exe,desk,root,apply);
 save("Stream",true,"Fermer Stream",false);Check(!Directory.Exists(desk),"enregistrer ne crée aucun raccourci");
 using(var f=new MainForm(store)){f.Show();Application.DoEvents();var button=Field<Button>(f,"shortcutButton");Check(button.Text=="Créer les raccourcis","création au pluriel");Check(button.BackColor==Color.FromArgb(18,115,104),"bouton contrasté");Call(f,"ApplyShortcut");Check(button.Text=="Mettre à jour les raccourcis","mise à jour au pluriel");Check(File.Exists(Path.Combine(desk,"Stream.lnk"))&&File.Exists(Path.Combine(desk,"Fermer Stream.lnk")),"bouton crée les deux raccourcis");using(var bitmap=new Bitmap(f.Width,f.Height)){f.DrawToBitmap(bitmap,new Rectangle(Point.Empty,f.Size));bitmap.Save(Path.Combine(root,"main.png"));}f.Close();}
 c=store.Read();g=c.Selected;byte[] launch=File.ReadAllBytes(Path.Combine(desk,"Stream.lnk")),closeBytes=File.ReadAllBytes(Path.Combine(desk,"Fermer Stream.lnk"));save("Jeux",true,"Fermer Jeux",false);Check(File.ReadAllBytes(Path.Combine(desk,"Stream.lnk")).SequenceEqual(launch)&&File.ReadAllBytes(Path.Combine(desk,"Fermer Stream.lnk")).SequenceEqual(closeBytes),"enregistrement conserve les raccourcis octet pour octet");
 using(var dialog=new GroupDialog(g,GroupLinks.FindClose(g,desk),(n,k,b,s)=>{})){Check(Field<TextBox>(dialog,"shortcutName").Text=="Fermer Jeux","réouverture conserve le nom non appliqué");}
 using(var f=new MainForm(store)){f.Show();Application.DoEvents();Check(Field<Catalog>(f,"catalog").Selected.Name=="Jeux","actualisation conserve les options non appliquées");Call(f,"ApplyShortcut");Check(File.Exists(Path.Combine(desk,"Jeux.lnk"))&&File.Exists(Path.Combine(desk,"Fermer Jeux.lnk"))&&!File.Exists(Path.Combine(desk,"Stream.lnk")),"bouton applique les deux renommages");f.Close();}
 c=store.Read();g=c.Selected;save("Jeux",false,"Fermer Jeux",false);Check(File.Exists(Path.Combine(desk,"Fermer Jeux.lnk")),"décocher et enregistrer ne supprime rien");using(var f=new MainForm(store)){f.Show();Application.DoEvents();Check(Field<Button>(f,"shortcutButton").Text=="Mettre à jour le raccourci","mise à jour au singulier");Call(f,"ApplyShortcut");Check(GroupLinks.FindClose(g,desk)==null&&File.Exists(Path.Combine(desk,"Jeux.lnk")),"bouton retire seulement le raccourci fermeture");f.Close();}
 c=store.Read();g=c.Selected;string collision=Path.Combine(desk,"Occupé.lnk");File.WriteAllText(collision,"ne pas toucher");save("Nouveau",true,"Occupé",false);bool refused=false;try{save("Nouveau",true,"Occupé",true);}catch(IOException){refused=true;}Check(refused&&File.Exists(Path.Combine(desk,"Jeux.lnk"))&&File.ReadAllText(collision)=="ne pas toucher","collision à application sans mutation");
 foreach(string color in GroupLinks.Colors){string path=GroupLinks.ExportIcon(color,root,true);using(var stream=typeof(Group).Assembly.GetManifestResourceStream("stop-"+color+".ico"))using(var ms=new MemoryStream()){stream.CopyTo(ms);Check(File.ReadAllBytes(path).SequenceEqual(ms.ToArray()),"icône stop embarquée "+color);}}
 save("Final",true,"Fermer Final",true);Type t=Type.GetTypeFromProgID("WScript.Shell");dynamic shell=Activator.CreateInstance(t);dynamic link=shell.CreateShortcut(Path.Combine(desk,"Fermer Final.lnk"));Check(((string)link.IconLocation).Contains("panda-stop-violet.ico"),"raccourci fermeture utilise stop violet");System.Runtime.InteropServices.Marshal.FinalReleaseComObject(link);System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shell);
 Console.WriteLine(count+" contrôles v9 réussis.");}
}
