using System;using System.IO;using System.Linq;using System.Drawing;using System.Reflection;using System.Windows.Forms;using PandaLauncher;
class RegressionV8 {
 static int n;static void Check(bool ok,string label){if(!ok)throw new Exception(label);Console.WriteLine("OK : "+label);n++;}
 static T Field<T>(object o,string name){return (T)o.GetType().GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(o);}
 [STAThread]static void Main(string[] args){Application.EnableVisualStyles();string root=args[0],desktop=Path.Combine(root,"Bureau"),exe=Path.Combine(root,"Panda Launcher.exe");var store=new CatalogStore(Path.Combine(root,"config.json"));var c=new Catalog();var g=c.Add("Ancien onglet");g.ShortcutName="Mon Bureau";store.Save(c);Check(g.Name=="Mon Bureau","migration conserve le nom du Bureau");GroupLinks.Update(g,g.Name,g.Icon,exe,desktop,root);store.Save(c);
 Action<string,bool,string> save=(name,enabled,close)=>GroupLinks.SavePreferences(store,c,g,name,"violet",enabled,close,exe,desktop,root,true);
 save("Travail",true,"Fermer — Travail");Check(g.Name==g.ShortcutName&&File.Exists(Path.Combine(desktop,"Travail.lnk")),"nom unique et renommage immédiat du lancement");Check(!File.Exists(Path.Combine(desktop,"Mon Bureau.lnk")),"ancien raccourci retiré");Check(File.Exists(Path.Combine(desktop,"Fermer — Travail.lnk"))&&store.Read().Selected.CloseShortcutEnabled==true,"fermeture créée et préférence persistée");
 using(var d=new GroupDialog(g,GroupLinks.FindClose(g,desktop),(name,color,enabled,close)=>{})){d.Show();Application.DoEvents();var name=Field<TextBox>(d,"groupName");var close=Field<TextBox>(d,"shortcutName");name.Text="Maison";Check(close.Text=="Fermer — Maison","nom automatique suit le launcher");close.Text="Tout fermer";name.Text="Loisirs";Check(close.Text=="Tout fermer","nom personnalisé conservé");var box=Field<CheckBox>(d,"closeEnabled");box.Checked=false;Check(!close.Visible,"champ masqué lorsque décoché");box.Checked=true;Application.DoEvents();var buttons=d.Controls[0].Controls.OfType<FlowLayoutPanel>().Last();Check(buttons.Bottom<=d.ClientSize.Height,"boutons visibles sans découpage");using(var bitmap=new Bitmap(d.Width,d.Height)){d.DrawToBitmap(bitmap,new Rectangle(Point.Empty,d.Size));bitmap.Save(Path.Combine(root,"parametres.png"));}d.Close();}
 save("Maison",true,"Tout fermer");Check(File.Exists(Path.Combine(desktop,"Tout fermer.lnk"))&&!File.Exists(Path.Combine(desktop,"Fermer — Travail.lnk")),"renommage du raccourci de fermeture");Check(g.CloseNameCustom,"personnalisation enregistrée");
 string collision=Path.Combine(desktop,"Occupé.lnk");File.WriteAllText(collision,"intouchable");bool refused=false;try{save("Autre",true,"Occupé");}catch(IOException){refused=true;}Check(refused&&g.Name=="Maison"&&File.ReadAllText(collision)=="intouchable"&&File.Exists(Path.Combine(desktop,"Maison.lnk")),"collision refuse sans mutation");
 string invalid=Path.Combine(root,"config-impossible");Directory.CreateDirectory(invalid);refused=false;try{GroupLinks.SavePreferences(new CatalogStore(invalid),c,g,"Échec","dore",true,"Fermer Échec",exe,desktop,root,true);}catch(IOException){refused=true;}Check(refused&&g.Name=="Maison"&&File.Exists(Path.Combine(desktop,"Maison.lnk"))&&File.Exists(Path.Combine(desktop,"Tout fermer.lnk"))&&!File.Exists(Path.Combine(desktop,"Échec.lnk")),"échec sauvegarde restaure les noms et raccourcis");
 save("Maison",false,"Tout fermer");Check(GroupLinks.FindClose(g,desktop)==null&&GroupLinks.Find(g,desktop)!=null,"décocher supprime seulement la fermeture");Check(store.Read().Selected.CloseShortcutEnabled==false,"désactivation persistée");var fresh=c.Add("Neuf");GroupLinks.SavePreferences(store,c,fresh,"Neuf","turquoise",false,"Fermer — Neuf",exe,desktop,root);Check(GroupLinks.Find(fresh,desktop)==null,"paramètres ne créent pas un lancement non demandé");Console.WriteLine(n+" contrôles v8 réussis.");}
}

