using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Diagnostics;
using System.Collections.Generic;
using PandaLauncher;
class Tests {
 static int count;static void Check(bool ok,string label){if(!ok)throw new Exception("ÉCHEC : "+label);Console.WriteLine("OK : "+label);count++;}
 static void AwaitFile(string path){for(int i=0;i<100&&!File.Exists(path);i++)Thread.Sleep(40);Check(File.Exists(path),"preuve de lancement "+Path.GetFileName(path));}
 [STAThread] static void Main(string[] args){
 string root=Path.GetFullPath(args[0]);Directory.CreateDirectory(root);string probe=Path.Combine(root,"Programme témoin.exe"),configPath=Path.Combine(root,"config.json");
 var store=new Store(configPath);Check(store.Read().Entries.Count==0,"configuration initiale vide");
 var c=new Configuration();var a=new Entry{Name="Écho & Panda",Target=probe,Arguments="\""+Path.Combine(root,"premier.txt")+"\" \"été & espace\"",WorkingDirectory=root,SkipRunning=false,DelayMs=200};var b=new Entry{Name="Désactivé",Target=Path.Combine(root,"absent.exe"),Enabled=false};c.Entries.Add(a);c.Entries.Add(b);store.Save(c);
 c=store.Read();Check(c.Entries.Count==2&&c.Entries[0].Id==a.Id,"ajout et persistance des identifiants");c.Entries[0].Name="Modifié";store.Save(c);Check(store.Read().Entries[0].Name=="Modifié","modification persistée");c.Entries.Reverse();store.Save(c);Check(store.Read().Entries[0].Id==b.Id,"réordonnancement persisté");c.Entries.RemoveAt(0);store.Save(c);Check(store.Read().Entries.Count==1,"suppression persistée");c.Entries.Add(b);store.Save(c);
 var states=new List<string>();int errors=Launcher.Run(store.Read(),(e,s,f)=>states.Add(s)).GetAwaiter().GetResult();Check(errors==0&&states.Count==1,"exclusion des désactivés");string output=Path.Combine(root,"premier.txt");AwaitFile(output);string[] lines=File.ReadAllLines(output);Check(lines[0]==root&&lines[1].Contains("été & espace"),"chemin accentué, espaces, arguments et dossier de travail");
 string link=Path.Combine(root,"témoin.lnk");Shortcuts.Create(probe,link);object shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));dynamic sh=shell;dynamic l=sh.CreateShortcut(link);l.Arguments="hérité";l.WorkingDirectory=root;l.Save();System.Runtime.InteropServices.Marshal.FinalReleaseComObject(l);System.Runtime.InteropServices.Marshal.FinalReleaseComObject(shell);
 var le=new Entry{Name="Lien",Target=link};var resolved=Shortcuts.Resolve(le);Check(resolved.Target==probe&&resolved.Arguments=="hérité"&&resolved.Directory==root,"héritage .lnk");le.Arguments="remplacé";Check(Shortcuts.Resolve(le).Arguments=="remplacé","remplacement des arguments .lnk");
 string desktopLink=Path.Combine(root,"Démarrer mon stream.lnk");Shortcuts.Create(Path.GetFullPath(args[1]),desktopLink);var before=File.ReadAllBytes(desktopLink);c.Entries[0].Arguments="\""+Path.Combine(root,"second.txt")+"\"";store.Save(c);Launcher.Run(store.Read(),(e,s,f)=>{}).GetAwaiter().GetResult();AwaitFile(Path.Combine(root,"second.txt"));Check(before.SequenceEqual(File.ReadAllBytes(desktopLink)),"modification prise en compte sans recréer le raccourci");
 c.Entries.Insert(0,new Entry{Name="Manquant",Target=Path.Combine(root,"missing.exe"),DelayMs=250});states.Clear();var timer=Stopwatch.StartNew();errors=Launcher.Run(c,(e,s,f)=>states.Add(s)).GetAwaiter().GetResult();Check(errors==1&&states.Count==2&&states[1].Contains("envoyée"),"fichier manquant et poursuite de la séquence");Check(timer.ElapsedMilliseconds>=250,"délai respecté");
 string running=Path.Combine(root,"running.txt");using(var p=Process.Start(new ProcessStartInfo(probe,"\""+running+"\" wait"){WorkingDirectory=root,UseShellExecute=false,CreateNoWindow=true})){AwaitFile(running);bool uncertain;Check(Launcher.IsRunning(probe,out uncertain),"détection par chemin du processus");string other=Path.Combine(root,"autre","Programme témoin.exe");Directory.CreateDirectory(Path.GetDirectoryName(other));File.Copy(probe,other,true);Check(!Launcher.IsRunning(other,out uncertain),"deux exécutables homonymes distingués");var one=new Configuration();one.Entries.Add(new Entry{Name="Déjà ouvert",Target=probe});states.Clear();Launcher.Run(one,(e,s,f)=>states.Add(s)).GetAwaiter().GetResult();Check(states.Single()=="Déjà ouvert","logiciel déjà ouvert ignoré");p.WaitForExit();}
 using(var gate=new LaunchLock(Launcher.LockName)){Check(gate.Acquired,"première séquence autorisée");bool blocked=false;var t=new Thread(()=>{using(var second=new LaunchLock(Launcher.LockName))blocked=!second.Acquired;});t.Start();t.Join();Check(blocked,"double séquence bloquée");}
 File.Copy(probe,Path.Combine(root,"probe.exe"),true);
 foreach(string ext in new[]{".cmd",".bat"}) {
  string script=Path.Combine(root,"script été & panda"+ext), proof=Path.Combine(root,"preuve"+ext+".txt");
  File.WriteAllText(script,"@echo off\r\n\"%~dp0probe.exe\" \"%~1\" \"%~2\"\r\n",System.Text.Encoding.ASCII);
  var batch=new Configuration();batch.Entries.Add(new Entry{Name="Script",Target=script,Arguments="\""+proof+"\" \"accent été & espace\"",WorkingDirectory=root});
  states.Clear();Check(Launcher.Run(batch,(e,s,f)=>states.Add(s)).GetAwaiter().GetResult()==0,"lancement "+ext);AwaitFile(proof);Check(File.ReadAllLines(proof)[1].Contains("accent été & espace"),"arguments script "+ext);Check(states.Single().Contains("détection indisponible"),"limite de détection explicite "+ext);
  string scriptLink=Path.Combine(root,"script"+ext+".lnk");object ws=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));dynamic w=ws;dynamic sl=w.CreateShortcut(scriptLink);sl.TargetPath=script;sl.Arguments="\""+proof+".lnk\" \"via lien\"";sl.WorkingDirectory=root;sl.Save();System.Runtime.InteropServices.Marshal.FinalReleaseComObject(sl);System.Runtime.InteropServices.Marshal.FinalReleaseComObject(ws);
  batch.Entries[0].Target=scriptLink;batch.Entries[0].Arguments="";batch.Entries[0].WorkingDirectory="";Check(Launcher.Run(batch,(e,s,f)=>{}).GetAwaiter().GetResult()==0,"lien vers script "+ext);AwaitFile(proof+".lnk");Check(File.ReadAllLines(proof+".lnk")[0]==root,"dossier hérité script "+ext);
 }
 string ps=Path.Combine(root,"script été & panda.ps1"),psProof=Path.Combine(root,"preuve ps1.txt");File.WriteAllText(ps,"param([string]$ResultPath, [string]$Value)\r\n[IO.File]::WriteAllLines($ResultPath, @([Environment]::CurrentDirectory, $Value))",new System.Text.UTF8Encoding(true));var psConfig=new Configuration();psConfig.Entries.Add(new Entry{Name="PowerShell",Target=ps,Arguments="\""+psProof+"\" \"été & panda\"",WorkingDirectory=root});string oldPolicy=Environment.GetEnvironmentVariable("PSExecutionPolicyPreference");try {Environment.SetEnvironmentVariable("PSExecutionPolicyPreference","RemoteSigned");Check(Launcher.Run(psConfig,(e,s,f)=>{}).GetAwaiter().GetResult()==0,"demande PowerShell (politique limitée au processus de test)");AwaitFile(psProof);}finally{Environment.SetEnvironmentVariable("PSExecutionPolicyPreference",oldPolicy);}Check(File.ReadAllLines(psProof)[1]=="été & panda","arguments PowerShell");Check(Launcher.BuildStart(Shortcuts.Resolve(psConfig.Entries[0]),true).Verb=="runas","élévation ciblée du script");Check(!Launcher.BuildStart(Shortcuts.Resolve(psConfig.Entries[0]),false).Arguments.Contains("Bypass"),"stratégie PowerShell non contournée");
 File.WriteAllText(configPath,"{invalide");bool rejected=false;try{store.Read();}catch(IOException){rejected=true;}Check(rejected&&File.ReadAllText(configPath)=="{invalide","JSON corrompu préservé");
 Console.WriteLine(count+" vérifications réussies.");
 }
}
