using System;using System.IO;using System.Linq;using System.Text;using System.Runtime.InteropServices;using Microsoft.Win32.SafeHandles;
namespace PandaLauncher {
// App execution aliases are Windows reparse points, not the running EXE's path.
public class ExecutionIdentity {
 public string PathName,Family,AliasTarget;
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern SafeFileHandle CreateFile(string path,uint access,uint share,IntPtr security,uint disposition,uint flags,IntPtr template);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool DeviceIoControl(SafeFileHandle file,uint code,IntPtr input,uint inputSize,byte[] output,uint outputSize,out uint returned,IntPtr overlapped);
 public string[] ProcessNames {get{return new[]{Path.GetFileNameWithoutExtension(PathName),AliasTarget==null?null:Path.GetFileNameWithoutExtension(AliasTarget)}.Where(n=>!String.IsNullOrEmpty(n)).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();}}
 public bool Matches(string candidate,string packageFamily){if(String.IsNullOrEmpty(candidate))return false;candidate=Path.GetFullPath(candidate);if(String.Equals(candidate,PathName,StringComparison.OrdinalIgnoreCase))return true;return Family!=null&&String.Equals(Family,packageFamily,StringComparison.OrdinalIgnoreCase)&&(String.Equals(candidate,AliasTarget,StringComparison.OrdinalIgnoreCase)||String.Equals(Path.GetFileName(candidate),Path.GetFileName(PathName),StringComparison.OrdinalIgnoreCase));}
 public static ExecutionIdentity Parse(string path,byte[] data,int count){var result=new ExecutionIdentity{PathName=System.IO.Path.GetFullPath(path)};if(count<12||count>data.Length||BitConverter.ToUInt32(data,0)!=0x8000001b)return result;int length=BitConverter.ToUInt16(data,4);if(length<4||length+8>count||BitConverter.ToUInt32(data,8)!=3||(length-4)%2!=0)return result;string[] fields=Encoding.Unicode.GetString(data,12,length-4).Split('\0');if(fields.Length<3||String.IsNullOrWhiteSpace(fields[0])||!fields[1].StartsWith(fields[0]+"!",StringComparison.Ordinal)||!System.IO.Path.IsPathRooted(fields[2])||!fields[2].EndsWith(".exe",StringComparison.OrdinalIgnoreCase))return result;result.Family=fields[0];result.AliasTarget=System.IO.Path.GetFullPath(fields[2]);return result;}
 public static ExecutionIdentity Read(string path){var fallback=new ExecutionIdentity{PathName=System.IO.Path.GetFullPath(path)};try{if((File.GetAttributes(path)&FileAttributes.ReparsePoint)==0)return fallback;using(var handle=CreateFile(path,0,7,IntPtr.Zero,3,0x00200000,IntPtr.Zero)){if(handle.IsInvalid)return fallback;var bytes=new byte[16384];uint count;if(DeviceIoControl(handle,0x900a8,IntPtr.Zero,0,bytes,(uint)bytes.Length,out count,IntPtr.Zero))return Parse(path,bytes,(int)count);}}catch(IOException){}catch(UnauthorizedAccessException){}return fallback;}
}
}
