using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Web.Script.Serialization;
namespace PandaLauncher {
public class Group : Configuration {
 public string Id=Guid.NewGuid().ToString("D");public string Name="Mon launcher";public string Icon="turquoise";public string ShortcutName="Mon launcher";public string ShortcutPath="";public string AppliedShortcutName;public bool NamesUnified;public bool? CloseShortcutEnabled;public string CloseShortcutName;public bool CloseNameCustom;
}
public class Catalog {
 public int Version=2;public string SelectedId;public string LegacyGroupId;public List<Group> Groups=new List<Group>();
 [ScriptIgnore] public Group Selected {get{return Groups.FirstOrDefault(g=>String.Equals(g.Id,SelectedId,StringComparison.OrdinalIgnoreCase))??Groups.First();}}
 public Group Add(string name){if(Groups.Count>=5)throw new InvalidOperationException("Vous pouvez conserver cinq launchers au maximum.");var g=new Group{Name=name,ShortcutName=name,Icon=GroupLinks.Colors[Groups.Count]};Groups.Add(g);SelectedId=g.Id;return g;}
 public Group ForLaunch(string id){string wanted=id??LegacyGroupId;if(String.IsNullOrEmpty(wanted))throw new IOException("Ce raccourci ne précise aucun launcher. Créez-le depuis Panda Launcher.");var g=Groups.FirstOrDefault(x=>String.Equals(x.Id,wanted,StringComparison.OrdinalIgnoreCase));if(g==null)throw new IOException("Ce launcher n’existe plus. Ouvrez Panda Launcher pour choisir un autre launcher.");return g;}
}
public class CatalogStore {
 public readonly string PathName;readonly string legacyPath;bool observed;string observedText;
 public CatalogStore(string path=null,string legacy=null){PathName=path??Path.Combine(Store.Root,"config.json");legacyPath=legacy??(path==null?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"PandaCoustik","StreamLauncher","config.json"):null);}
 public Catalog Read(){
  if(!File.Exists(PathName)){observed=true;observedText=null;var c=new Catalog();var g=c.Add("Mon launcher");if(legacyPath!=null&&File.Exists(legacyPath)){g.Entries=new Store(legacyPath).Read().Entries;c.LegacyGroupId=g.Id;}return c;}
  try{string text=File.ReadAllText(PathName);var c=new JavaScriptSerializer().Deserialize<Catalog>(text);Validate(c);observed=true;observedText=text;return c;}catch(Exception ex){throw new IOException("Configuration illisible, conservée sans modification : "+PathName+"\n"+ex.Message,ex);}
 }
 public static void Validate(Catalog c){
  if(c==null||c.Version!=2||c.Groups==null||c.Groups.Count<1||c.Groups.Count>5)throw new IOException("Catalogue de launchers invalide.");var ids=new HashSet<string>(StringComparer.OrdinalIgnoreCase);
  foreach(var g in c.Groups){Guid guid;if(g==null||!Guid.TryParseExact(g.Id,"D",out guid)||!ids.Add(g.Id)||String.IsNullOrWhiteSpace(g.Name)||g.Name.Length>100||!GroupLinks.Colors.Contains(g.Icon)||g.Entries==null)throw new IOException("Launcher invalide.");var entries=new HashSet<string>();foreach(var e in g.Entries)if(e==null||String.IsNullOrWhiteSpace(e.Id)||!entries.Add(e.Id)||String.IsNullOrWhiteSpace(e.Name)||String.IsNullOrWhiteSpace(e.Target)||!Path.IsPathRooted(e.Target)||e.DelayMs<0||e.DelayMs>600000||e.WaitMode<0||e.WaitMode>2||e.WaitTimeoutSeconds<1||e.WaitTimeoutSeconds>600)throw new IOException("Entrée invalide dans « "+g.Name+" ».");if(!g.NamesUnified){g.Name=String.IsNullOrWhiteSpace(g.ShortcutName)?g.Name:g.ShortcutName;g.ShortcutName=g.Name;g.NamesUnified=true;}GroupLinks.ValidateName(g.Name);if(g.Name.Length>100)throw new IOException("Nom migré invalide.");g.Entries=g.Entries.OrderBy(e=>e.Position).ToList();}
  if(!ids.Contains(c.SelectedId))c.SelectedId=c.Groups[0].Id;
 }
 public void Save(Catalog c){if(observed&&(File.Exists(PathName)?File.ReadAllText(PathName):null)!=observedText)throw new IOException("La configuration a été modifiée ailleurs. Rouvrez Panda Launcher avant de réessayer.");Validate(c);foreach(var g in c.Groups)for(int i=0;i<g.Entries.Count;i++)g.Entries[i].Position=i;Validate(c);Directory.CreateDirectory(Path.GetDirectoryName(PathName));string tmp=PathName+"."+Guid.NewGuid().ToString("N")+".tmp";try{var bytes=System.Text.Encoding.UTF8.GetBytes(new JavaScriptSerializer().Serialize(c));using(var f=new FileStream(tmp,FileMode.CreateNew,FileAccess.Write,FileShare.None)){f.Write(bytes,0,bytes.Length);f.Flush(true);}if(File.Exists(PathName))File.Replace(tmp,PathName,PathName+".bak");else File.Move(tmp,PathName);observedText=System.Text.Encoding.UTF8.GetString(bytes);observed=true;}finally{if(File.Exists(tmp))File.Delete(tmp);}}
}
public static class GroupLinks {
 [DllImport("shell32.dll",CharSet=CharSet.Unicode)] static extern void SHChangeNotify(uint eventId,uint flags,string item1,string item2);
 static void Notify(string old,string destination){if(old!=null&&!String.Equals(old,destination,StringComparison.Ordinal))SHChangeNotify(1,0x1005,old,destination);else SHChangeNotify(0x2000,0x1005,destination,null);SHChangeNotify(0x1000,0x1005,Path.GetDirectoryName(destination),null);}
 public static bool SynchronizeExternalName(Group group,string found){if(found==null)return false;string actual=Path.GetFileNameWithoutExtension(found),applied=group.AppliedShortcutName??(String.IsNullOrEmpty(group.ShortcutPath)?group.ShortcutName:Path.GetFileNameWithoutExtension(group.ShortcutPath));bool changed=false;if(String.Equals(group.ShortcutName,applied,StringComparison.Ordinal)&&group.ShortcutName!=actual){group.ShortcutName=actual;group.Name=actual;changed=true;}if(group.ShortcutPath!=found||group.AppliedShortcutName!=actual){group.ShortcutPath=found;group.AppliedShortcutName=actual;changed=true;}return changed;}
 public static readonly string[] Colors={"turquoise","violet","fuchsia","emeraude","dore"};
 public static readonly string[] Labels={"Turquoise","Violet","Fuchsia","Émeraude","Doré"};
 public static string Desktop {get{return Environment.GetFolderPath(Environment.SpecialFolder.DesktopDirectory);}}
 public static string Arguments(string id){return "--launch --group "+id;}
 public static string Marker(string id){return "PandaLauncher:"+id;}
 public static bool Belongs(string file,string id){if(!File.Exists(file))return false;object shell=null,link=null;try{shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));dynamic s=shell;link=s.CreateShortcut(file);dynamic l=link;return String.Equals(((string)l.Arguments).Trim(),Arguments(id),StringComparison.Ordinal)&&((string)l.Description).StartsWith(Marker(id),StringComparison.Ordinal);}catch{return false;}finally{Release(link);Release(shell);}}
 static void Release(object o){if(o!=null)Marshal.FinalReleaseComObject(o);}
 public static string Find(Group group,string desktop){if(!Directory.Exists(desktop))return null;var matches=Directory.GetFiles(desktop,"*.lnk").Where(p=>Belongs(p,group.Id)).ToList();if(matches.Count>1)throw new IOException("Plusieurs raccourcis correspondent au launcher « "+group.Name+" ». Conservez une seule copie sur le Bureau avant de le modifier.");return matches.SingleOrDefault();}
 public static void ValidateName(string name){if(String.IsNullOrWhiteSpace(name)||name.Length>100||name!=name.Trim()||name.EndsWith(".")||name.IndexOfAny(Path.GetInvalidFileNameChars())>=0||System.Text.RegularExpressions.Regex.IsMatch(name,@"^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\.|$)",System.Text.RegularExpressions.RegexOptions.IgnoreCase))throw new IOException("Choisissez un nom de raccourci valide (1 à 100 caractères, sans \\ / : * ? \" < > |).");}
 public static string ExportIcon(string color,string root=null,bool closing=false){if(!Colors.Contains(color))throw new IOException("Icône inconnue.");string path=Path.Combine(root??Store.Root,"icons","panda-"+(closing?"stop-":"run-")+color+".ico");using(var source=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream((closing?"stop-":"run-")+color+".ico")){if(source==null)throw new IOException("Icône embarquée manquante.");Directory.CreateDirectory(Path.GetDirectoryName(path));using(var ms=new MemoryStream()){source.CopyTo(ms);var bytes=ms.ToArray();if(!File.Exists(path)||!File.ReadAllBytes(path).SequenceEqual(bytes))File.WriteAllBytes(path,bytes);}}return path;}
 public static string Update(Group group,string name,string color,string exe,string desktop,string iconRoot=null){
  ValidateName(name);string old=Find(group,desktop),destination=Path.Combine(desktop,name+".lnk");if(File.Exists(destination)&&!Belongs(destination,group.Id))throw new IOException("Ce nom est déjà utilisé par un autre raccourci. Choisissez un autre nom.");
  Directory.CreateDirectory(desktop);string icon=ExportIcon(color,iconRoot),tmp=Path.Combine(desktop,".panda-"+Guid.NewGuid().ToString("N")+".lnk");object shell=null,link=null;
  try{shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));dynamic s=shell;link=s.CreateShortcut(tmp);dynamic l=link;l.TargetPath=exe;l.Arguments=Arguments(group.Id);l.WorkingDirectory=Path.GetDirectoryName(exe);l.Description=Marker(group.Id)+" | "+group.Name;l.IconLocation=icon+",0";l.Save();Release(link);link=null;if(File.Exists(destination))File.Replace(tmp,destination,null);else File.Move(tmp,destination);
   if(old!=null&&String.Equals(old,destination,StringComparison.OrdinalIgnoreCase)&&!String.Equals(old,destination,StringComparison.Ordinal)){string interim=Path.Combine(desktop,".rename-"+Guid.NewGuid().ToString("N")+".lnk");File.Move(old,interim);try{File.Move(interim,destination);}catch{File.Move(interim,old);throw;}}
   if(old!=null&&!String.Equals(old,destination,StringComparison.OrdinalIgnoreCase)){if(!Belongs(old,group.Id))throw new IOException("Le raccourci a changé pendant la mise à jour.");File.Delete(old);}
   string verified=Find(group,desktop);if(verified==null||!String.Equals(Path.GetFileName(verified),name+".lnk",StringComparison.Ordinal))throw new IOException("Le nouveau nom du raccourci n’a pas pu être confirmé sur disque.");
   Notify(old,destination);group.ShortcutName=name;group.AppliedShortcutName=name;group.ShortcutPath=destination;group.Icon=color;return destination;}finally{Release(link);Release(shell);if(File.Exists(tmp))File.Delete(tmp);}
 }
 public static bool IsCloseLink(string file,string id){object shell=null,link=null;try{shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));dynamic s=shell;link=s.CreateShortcut(file);dynamic l=link;return (string)l.Arguments=="--close --group "+id&&(string)l.Description==Marker(id)+":close";}catch{return false;}finally{Release(link);Release(shell);}}
 public static string CreateClose(Group group,string exe,string desktop,string iconRoot=null,string requestedName=null){
  Directory.CreateDirectory(desktop);var matches=Directory.GetFiles(desktop,"*.lnk").Where(p=>IsCloseLink(p,group.Id)).ToList();if(matches.Count>1)throw new IOException("Plusieurs raccourcis de fermeture sont associés à ce launcher.");
  string name=requestedName??("Fermer — "+group.ShortcutName);ValidateName(name);string old=matches.SingleOrDefault();string destination=requestedName==null&&old!=null?old:Path.Combine(desktop,name+".lnk");if(File.Exists(destination)&&!IsCloseLink(destination,group.Id))throw new IOException("Ce nom est déjà utilisé par un autre raccourci.");
  string tmp=Path.Combine(desktop,".panda-close-"+Guid.NewGuid().ToString("N")+".lnk");object shell=null,link=null;try{shell=Activator.CreateInstance(Type.GetTypeFromProgID("WScript.Shell"));dynamic s=shell;link=s.CreateShortcut(tmp);dynamic l=link;l.TargetPath=exe;l.Arguments="--close --group "+group.Id;l.Description=Marker(group.Id)+":close";l.WorkingDirectory=Path.GetDirectoryName(exe);l.IconLocation=ExportIcon(group.Icon,iconRoot,true)+",0";l.Save();Release(link);link=null;if(File.Exists(destination))File.Replace(tmp,destination,null);else File.Move(tmp,destination);if(old!=null&&!String.Equals(old,destination,StringComparison.OrdinalIgnoreCase))File.Delete(old);if(old!=null&&String.Equals(old,destination,StringComparison.OrdinalIgnoreCase)&&old!=destination){string interim=tmp+".lnk";File.Move(old,interim);try{File.Move(interim,destination);}catch{File.Move(interim,old);throw;}}Notify(old,destination);return destination;}finally{Release(link);Release(shell);if(File.Exists(tmp))File.Delete(tmp);}
 }
 public static string FindClose(Group group,string desktop){if(!Directory.Exists(desktop))return null;var matches=Directory.GetFiles(desktop,"*.lnk").Where(p=>IsCloseLink(p,group.Id)).ToList();if(matches.Count>1)throw new IOException("Plusieurs raccourcis de fermeture correspondent à ce launcher.");return matches.SingleOrDefault();}
 public static string DefaultCloseName(string name){return "Fermer — "+name;}
 public static void SavePreferences(CatalogStore store,Catalog catalog,Group group,string name,string color,bool closeEnabled,string closeName,string exe,string desktop,string iconRoot=null,bool apply=false){
  ValidateName(name);if(name.Length>90)throw new IOException("Le nom du launcher est limité à 90 caractères.");if(!Colors.Contains(color))throw new IOException("Couleur inconnue.");if(closeEnabled){ValidateName(closeName);if(String.Equals(name,closeName,StringComparison.OrdinalIgnoreCase))throw new IOException("Les deux raccourcis doivent avoir des noms différents.");}
  if(!apply){var copy=new JavaScriptSerializer().Deserialize<Group>(new JavaScriptSerializer().Serialize(group));try{group.Name=group.ShortcutName=name;group.NamesUnified=true;group.Icon=color;group.CloseShortcutEnabled=closeEnabled;group.CloseShortcutName=closeName;group.CloseNameCustom=closeName!=DefaultCloseName(name);store.Save(catalog);}catch{foreach(var field in typeof(Group).GetFields())field.SetValue(group,field.GetValue(copy));throw;}return;}
  string launch=Find(group,desktop),close=FindClose(group,desktop);string launchDest=Path.Combine(desktop,name+".lnk"),closeDest=Path.Combine(desktop,closeName+".lnk");
  if(File.Exists(launchDest)&&!Belongs(launchDest,group.Id))throw new IOException("Le nom du launcher est déjà utilisé sur le Bureau.");
  if(closeEnabled&&File.Exists(closeDest)&&!IsCloseLink(closeDest,group.Id))throw new IOException("Le nom du raccourci de fermeture est déjà utilisé sur le Bureau.");
  var serializer=new JavaScriptSerializer();var before=serializer.Deserialize<Group>(serializer.Serialize(group));var backups=new Dictionary<string,byte[]>(StringComparer.OrdinalIgnoreCase);foreach(string path in new[]{launch,close,launchDest,closeEnabled?closeDest:null}.Where(p=>p!=null).Distinct(StringComparer.OrdinalIgnoreCase))backups[path]=File.Exists(path)?File.ReadAllBytes(path):null;
  try{group.Name=name;group.ShortcutName=name;group.NamesUnified=true;group.Icon=color;group.CloseShortcutEnabled=closeEnabled;group.CloseShortcutName=closeName;group.CloseNameCustom=closeName!=DefaultCloseName(name);
   Update(group,name,color,exe,desktop,iconRoot);if(closeEnabled)CreateClose(group,exe,desktop,iconRoot,closeName);else if(close!=null)File.Delete(close);store.Save(catalog);
   }catch(Exception failure){var restoreErrors=new List<string>();foreach(var f in backups){try{if(f.Value==null){if(File.Exists(f.Key))File.Delete(f.Key);}else if(!File.Exists(f.Key)||!File.ReadAllBytes(f.Key).SequenceEqual(f.Value))File.WriteAllBytes(f.Key,f.Value);}catch(Exception restore){restoreErrors.Add(f.Key+" : "+restore.Message);}}foreach(var field in typeof(Group).GetFields())field.SetValue(group,field.GetValue(before));if(restoreErrors.Count>0)throw new IOException(failure.Message+"\nRestauration incomplète :\n"+String.Join("\n",restoreErrors),failure);throw;}
 }
 public static void Delete(CatalogStore store,Catalog catalog,Group group,string desktop){
  if(catalog.Groups.Count<=1||!catalog.Groups.Contains(group))throw new IOException("Le dernier launcher ne peut pas être supprimé.");
  string launch=Find(group,desktop),close=FindClose(group,desktop),selected=catalog.SelectedId;int index=catalog.Groups.IndexOf(group);var backups=new Dictionary<string,byte[]>();foreach(string path in new[]{launch,close}.Where(p=>p!=null))backups[path]=File.ReadAllBytes(path);
  try{foreach(string path in backups.Keys)File.Delete(path);catalog.Groups.Remove(group);catalog.SelectedId=catalog.Groups[0].Id;store.Save(catalog);}catch(Exception failure){if(!catalog.Groups.Contains(group))catalog.Groups.Insert(index,group);catalog.SelectedId=selected;var errors=new List<string>();foreach(var pair in backups){try{if(!File.Exists(pair.Key)||!File.ReadAllBytes(pair.Key).SequenceEqual(pair.Value))File.WriteAllBytes(pair.Key,pair.Value);}catch(Exception ex){errors.Add(ex.Message);}}if(errors.Count>0)throw new IOException(failure.Message+"\nRestauration incomplète : "+String.Join(" ; ",errors),failure);throw;}
 }
 public static void Remove(Group group,string desktop){string found=Find(group,desktop);if(found!=null&&Belongs(found,group.Id))File.Delete(found);if(Directory.Exists(desktop))foreach(string p in Directory.GetFiles(desktop,"*.lnk"))if(IsCloseLink(p,group.Id))File.Delete(p);}
}
}





