using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Diagnostics;using System.Threading.Tasks;
namespace PandaLauncher {
public class DropBatch {
 public List<Entry> Added=new List<Entry>();public List<string> Issues=new List<string>();
 public static DropBatch Prepare(IEnumerable<string> files,IEnumerable<Entry> existing){var batch=new DropBatch();var known=existing.ToList();foreach(string file in files){try{if(!File.Exists(file)||!Shortcuts.Supported(file)){batch.Issues.Add(Path.GetFileName(file)+" : fichier non pris en charge");continue;}var entry=new Entry{Name=Path.GetFileNameWithoutExtension(file),Target=Path.GetFullPath(file),WorkingDirectory=Path.GetExtension(file).Equals(".lnk",StringComparison.OrdinalIgnoreCase)?"":Path.GetDirectoryName(Path.GetFullPath(file))};var duplicate=Entries.FindDuplicate(known,entry);if(duplicate!=null){batch.Issues.Add(entry.Name+" : déjà présent (« "+duplicate.Name+" »)");continue;}batch.Added.Add(entry);known.Add(entry);}catch(Exception ex){batch.Issues.Add(Path.GetFileName(file)+" : "+ex.Message);}}return batch;}
}
public static class AppCloser {
 delegate bool WindowVisitor(IntPtr window,IntPtr parameter);
 [System.Runtime.InteropServices.DllImport("user32.dll")]static extern bool EnumWindows(WindowVisitor callback,IntPtr parameter);
 [System.Runtime.InteropServices.DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr window,out uint process);
 [System.Runtime.InteropServices.DllImport("user32.dll",SetLastError=true)]static extern bool PostMessage(IntPtr window,uint message,IntPtr wparam,IntPtr lparam);
 [System.Runtime.InteropServices.DllImport("user32.dll")]static extern bool IsWindowVisible(IntPtr window);
 [System.Runtime.InteropServices.DllImport("user32.dll",CharSet=System.Runtime.InteropServices.CharSet.Unicode)]static extern int GetWindowTextLength(IntPtr window);
 static bool RequestClose(int processId,out bool denied){bool sent=false,blocked=false;EnumWindows((window,parameter)=>{uint owner;GetWindowThreadProcessId(window,out owner);if(owner==(uint)processId&&(IsWindowVisible(window)||GetWindowTextLength(window)>0)){if(PostMessage(window,0x0010,IntPtr.Zero,IntPtr.Zero))sent=true;else if(System.Runtime.InteropServices.Marshal.GetLastWin32Error()==5)blocked=true;}return true;},IntPtr.Zero);denied=blocked;return sent;}
 [System.Runtime.InteropServices.DllImport("kernel32.dll",SetLastError=true)]static extern IntPtr OpenProcess(int access,bool inherit,int pid);
 [System.Runtime.InteropServices.DllImport("kernel32.dll")]static extern bool CloseHandle(IntPtr handle);
 [System.Runtime.InteropServices.DllImport("kernel32.dll",SetLastError=true)]static extern bool GetProcessTimes(IntPtr handle,out long created,out long exited,out long kernel,out long user);
 public static long StartedAt(int pid){IntPtr h=OpenProcess(0x1000,false,pid);if(h==IntPtr.Zero)throw new System.ComponentModel.Win32Exception();try{long c,e,k,u;if(!GetProcessTimes(h,out c,out e,out k,out u))throw new System.ComponentModel.Win32Exception();return DateTime.FromFileTimeUtc(c).Ticks;}finally{CloseHandle(h);}}
 [System.Runtime.InteropServices.DllImport("kernel32.dll",CharSet=System.Runtime.InteropServices.CharSet.Unicode,SetLastError=true)]static extern bool QueryFullProcessImageName(IntPtr handle,int flags,System.Text.StringBuilder text,ref int size);
 [System.Runtime.InteropServices.DllImport("kernel32.dll",SetLastError=true)]static extern bool TerminateProcess(IntPtr handle,uint exitCode);
 sealed class Target : IDisposable {public Process Process;public int Id;public string Path;public long Ticks;public void Dispose(){Process.Dispose();}}
 static bool Alive(Target p){IntPtr h=OpenProcess(0x1000,false,p.Id);if(h!=IntPtr.Zero){try{long c,e,k,u;if(GetProcessTimes(h,out c,out e,out k,out u))return e==0&&DateTime.FromFileTimeUtc(c).Ticks==p.Ticks;}finally{CloseHandle(h);}}using(var candidate=FindProcess(p.Id))return candidate!=null;}
 static Process FindProcess(int pid){try{return Process.GetProcessById(pid);}catch(ArgumentException){return null;}}
 // Keep one OS handle open from validation through action, preventing PID reuse.
 public static bool ActOnProcess(int pid,long ticks,string path,bool force){using(var self=Process.GetCurrentProcess())if(pid==self.Id)throw new IOException("Le launcher ne peut pas se fermer lui-même.");IntPtr h=OpenProcess(force?0x1001:0x1000,false,pid);if(h==IntPtr.Zero)throw new System.ComponentModel.Win32Exception();try{long c,e,k,u;var actual=new System.Text.StringBuilder(32768);int size=actual.Capacity;if(!GetProcessTimes(h,out c,out e,out k,out u)||!QueryFullProcessImageName(h,0,actual,ref size))throw new System.ComponentModel.Win32Exception();if(DateTime.FromFileTimeUtc(c).Ticks!=ticks||!String.Equals(actual.ToString(),path,StringComparison.OrdinalIgnoreCase))throw new IOException("L’identité du processus a changé.");if(force){if(!TerminateProcess(h,1))throw new System.ComponentModel.Win32Exception();return true;}bool denied;bool sent=RequestClose(pid,out denied);if(denied)throw new System.ComponentModel.Win32Exception(5);return sent;}finally{CloseHandle(h);}}
 static async Task<bool> Act(Target p,bool force,Entry entry,Func<Entry,bool> confirmElevation){if(!Alive(p))return false;string path=p.Path;long ticks=p.Ticks;if(path==null)throw new IOException("Identité du processus inaccessible.");try{return ActOnProcess(p.Id,ticks,path,force);}catch(System.ComponentModel.Win32Exception ex){if(ex.NativeErrorCode!=5)throw;}return await WithElevationConsent(entry,confirmElevation,()=>RequestElevated(p,force,path,ticks));}
 public static async Task<bool> WithElevationConsent(Entry entry,Func<Entry,bool> confirm,Func<Task<bool>> request){if(confirm==null||!confirm(entry))throw new OperationCanceledException("Fermeture administrateur annulée ; logiciel laissé ouvert.");return await request();}
 static async Task<bool> RequestElevated(Target p,bool force,string path,long ticks){string args="--process-action "+p.Id+" "+ticks+" "+(force?"force":"close")+" "+Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(path));Process elevated;try{elevated=Process.Start(new ProcessStartInfo(System.Windows.Forms.Application.ExecutablePath,args){UseShellExecute=true,Verb="runas"});}catch(System.ComponentModel.Win32Exception ex){if(ex.NativeErrorCode==1223)throw new OperationCanceledException("Autorisation administrateur annulée ; logiciel laissé ouvert.");throw;}using(var helper=elevated){await Task.Run(()=>helper.WaitForExit());if(helper.ExitCode!=0)throw new IOException("Fermeture administrateur refusée ou échouée.");return true;}}
 public static async Task<int> Close(Configuration config,Action<Entry,string,bool> report,Func<Entry,bool> confirmForce=null,int timeoutMs=8000,Func<Entry,bool> confirmElevation=null){int failures=0;foreach(var entry in config.Entries.OrderByDescending(e=>e.Position)){var matches=new List<Target>();try{var resolved=Shortcuts.Resolve(entry);if(!resolved.CanDetectRunning){failures++;report(entry,"Fermeture manuelle : cible script non identifiable",true);continue;}var identity=ExecutionIdentity.Read(resolved.Target);bool uncertain=false;var ids=new HashSet<int>();
  foreach(string name in identity.ProcessNames)foreach(var p in Process.GetProcessesByName(name)){bool keep=false;try{string path=Launcher.ProcessPath(p.Id);if(path==null){uncertain=true;continue;}if(!identity.Matches(path,identity.Family==null?null:Launcher.PackageFamily(p.Id)))continue;if(p.Id==Process.GetCurrentProcess().Id){uncertain=true;continue;}if(ids.Add(p.Id)){matches.Add(new Target{Process=p,Id=p.Id,Path=path,Ticks=StartedAt(p.Id)});keep=true;}}catch(InvalidOperationException){}catch(System.ComponentModel.Win32Exception){uncertain=true;}finally{if(!keep)p.Dispose();}}
  if(matches.Count==0){report(entry,uncertain?"Fermeture impossible : identité inaccessible":"Déjà fermé",uncertain);if(uncertain)failures++;continue;}
  bool requested=false;foreach(var p in matches){try{if(await Act(p,false,entry,confirmElevation))requested=true;}catch(InvalidOperationException){}catch(OperationCanceledException){throw;}catch(Exception ex){report(entry,"Fermeture normale : "+ex.Message,true);}}
  report(entry,requested?"Fermeture en cours…":"Processus actif en arrière-plan",false);
  var timer=Stopwatch.StartNew();while(requested&&matches.Any(p=>Alive(p))&&timer.ElapsedMilliseconds<timeoutMs)await Task.Delay(200);
  if(matches.Any(p=>Alive(p))&&confirmForce!=null&&confirmForce(entry)){foreach(var p in matches)if(Alive(p))await Act(p,true,entry,confirmElevation);timer.Restart();while(matches.Any(p=>Alive(p))&&timer.ElapsedMilliseconds<3000)await Task.Delay(100);}
  bool unknown;bool running=Launcher.IsRunning(resolved.Target,out unknown);if(!running&&!unknown)report(entry,"Application fermée",false);else{failures++;report(entry,running?"Toujours actif · processus détecté":"État inconnu · accès refusé",true);}
 }catch(Exception ex){failures++;report(entry,"Erreur de fermeture : "+ex.Message,true);Journal.Write(entry.Name+" : fermeture : "+ex.Message);}finally{foreach(var p in matches)p.Dispose();}}return failures;}
}
}






