using System;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Windows.Forms;

namespace PandaLauncher {
public static class Theme {
 public static readonly Color Background=Color.FromArgb(240,242,248),Surface=Color.White,Muted=Color.FromArgb(91,102,124),Accent=Color.FromArgb(101,75,206),Ink=Color.FromArgb(34,42,60);
 public static void Apply(Control c) {c.BackColor=Background;c.ForeColor=Ink;c.Font=new Font("Segoe UI",10);foreach(Control child in c.Controls)Apply(child);if(c is Button){var b=(Button)c;b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderSize=0;b.UseVisualStyleBackColor=false;b.BackColor=Surface;b.AutoSize=true;b.Padding=new Padding(9,5,9,5);b.Cursor=Cursors.Hand;}if(c is Form){var f=(Form)c;f.Icon=AppIcon();}if(c is TextBox){((TextBox)c).BorderStyle=BorderStyle.FixedSingle;c.BackColor=Surface;}if(c is NumericUpDown)c.BackColor=Surface;}
 public static Button Button(string text,Action action){var b=new SoftButton{Text=text,AutoSize=true,Margin=new Padding(0,0,8,0)};b.Click+=(s,e)=>action();return b;}
 public static Image Logo(bool launch){return ResourceImage(launch?"run-turquoise.png":"editor.png");}
 public static Image RunLogo(string color){return ResourceImage("run-"+color+".png");}
 static Image ResourceImage(string resource){var s=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream(resource);if(s==null)return null;using(s)using(var source=Image.FromStream(s))return new Bitmap(source);}
 public static Icon AppIcon(){return Icon.ExtractAssociatedIcon(Application.ExecutablePath);}
 public static void Primary(Button button){button.BackColor=Accent;button.ForeColor=Color.White;button.Font=new Font("Segoe UI Semibold",11);}
}
public class SoftButton : Button {
 bool hovered,pressed;
 public SoftButton(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.ResizeRedraw,true);}
 protected override void OnPaintBackground(PaintEventArgs e){e.Graphics.Clear(Parent==null?Theme.Background:Parent.BackColor);}
 protected override void OnMouseEnter(EventArgs e){hovered=true;Invalidate();base.OnMouseEnter(e);}
 protected override void OnMouseLeave(EventArgs e){hovered=false;pressed=false;Invalidate();base.OnMouseLeave(e);}
 protected override void OnMouseDown(MouseEventArgs e){pressed=e.Button==MouseButtons.Left;Invalidate();base.OnMouseDown(e);}
 protected override void OnMouseUp(MouseEventArgs e){pressed=false;Invalidate();base.OnMouseUp(e);}
 protected override void OnEnabledChanged(EventArgs e){Invalidate();base.OnEnabledChanged(e);}
 protected override void OnPaint(PaintEventArgs e){e.Graphics.Clear(Parent==null?Theme.Background:Parent.BackColor);e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;var r=new Rectangle(2,2,Width-5,Height-5);if(r.Width<2||r.Height<2)return;using(var path=new System.Drawing.Drawing2D.GraphicsPath()){int d=Math.Min(14,Math.Min(r.Width,r.Height));path.AddArc(r.X,r.Y,d,d,180,90);path.AddArc(r.Right-d,r.Y,d,d,270,90);path.AddArc(r.Right-d,r.Bottom-d,d,d,0,90);path.AddArc(r.X,r.Bottom-d,d,d,90,90);path.CloseFigure();Color fill=!Enabled?Color.FromArgb(227,230,237):pressed?ControlPaint.Dark(BackColor,0.08f):hovered?ControlPaint.Light(BackColor,0.12f):BackColor;using(var brush=new SolidBrush(fill))e.Graphics.FillPath(brush,path);using(var pen=new Pen(Focused?Theme.Accent:BackColor==Theme.Accent?Theme.Accent:Color.FromArgb(203,209,222),Focused?2:1))e.Graphics.DrawPath(pen,path);}TextRenderer.DrawText(e.Graphics,Text,Font,r,Enabled?ForeColor:Theme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis);}
}
public class Editor : Form {
 TextBox name=new TextBox(),target=new TextBox(),args=new TextBox(),folder=new TextBox();
 CheckBox skip=new CheckBox{Text="Ne pas relancer si déjà ouvert",AutoSize=true},admin=new CheckBox{Text="Lancer en administrateur (demande Windows)",AutoSize=true};
 NumericUpDown delay=new NumericUpDown{Minimum=0,Maximum=600,DecimalPlaces=1,Increment=0.5m};
 ComboBox waitMode=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=590};NumericUpDown waitTimeout=new NumericUpDown{Minimum=1,Maximum=600,Value=60,Width=120};
 public Entry Result;
 public Editor(Entry original,Func<Entry,string> validate=null) {
  Text=original==null?"Ajouter un logiciel":"Modifier le logiciel";Size=new Size(690,370);MinimumSize=Size;StartPosition=FormStartPosition.CenterParent;
  var root=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.TopDown,WrapContents=false,Padding=new Padding(14),AutoScroll=true};Controls.Add(root);
  target.Width=590;name.Width=590;args.Width=590;folder.Width=590;
  root.Controls.Add(new Label{Text="APPLICATION, SCRIPT OU RACCOURCI",AutoSize=true});root.Controls.Add(target);
  root.Controls.Add(Theme.Button("Parcourir…",()=>Browse()));root.Controls.Add(new Label{Text="Nom affiché",AutoSize=true});root.Controls.Add(name);
  var advanced=new FlowLayoutPanel{Width=625,Height=462,FlowDirection=FlowDirection.TopDown,WrapContents=false,Visible=false};
  root.Controls.Add(Theme.Button("Options avancées ▾",()=>{advanced.Visible=!advanced.Visible;Height=advanced.Visible?Math.Min(870,Screen.FromControl(this).WorkingArea.Height-30):370;}));root.Controls.Add(advanced);
  advanced.Controls.Add(new Label{Text="Arguments (vide : héritage du .lnk)",AutoSize=true});advanced.Controls.Add(args);
  advanced.Controls.Add(new Label{Text="Dossier de travail (vide : .lnk, puis dossier de la cible)",AutoSize=true});advanced.Controls.Add(folder);
  advanced.Controls.Add(new Label{Text="Avant de passer au logiciel suivant",AutoSize=true});waitMode.Items.AddRange(new object[]{"Ne pas attendre de confirmation","Attendre que le processus soit détecté","Attendre une fenêtre visible et réactive"});waitMode.SelectedIndex=original==null?1:original.WaitMode;advanced.Controls.Add(waitMode);
  advanced.Controls.Add(new Label{Text="Attente maximale (secondes) — la suite est arrêtée si elle échoue",AutoSize=true});waitTimeout.Value=original==null?60:original.WaitTimeoutSeconds;advanced.Controls.Add(waitTimeout);
  advanced.Controls.Add(new Label{Text="Délai supplémentaire avant le logiciel suivant (secondes)",AutoSize=true});advanced.Controls.Add(delay);advanced.Controls.Add(skip);advanced.Controls.Add(admin);
  advanced.Controls.Add(new Label{Text="Une fenêtre réactive ne garantit pas que les plugins ou connexions soient prêts.",AutoSize=true});
  advanced.Controls.Add(new Label{Text="Une valeur renseignée remplace celle du raccourci.\nScripts : lancement autorisé, sans détection fiable « déjà ouvert ».\nPowerShell : la stratégie d’exécution Windows reste respectée.",AutoSize=true});
  var buttons=new FlowLayoutPanel{Width=600,Height=48};root.Controls.Add(buttons);
  buttons.Controls.Add(Theme.Button("Enregistrer",()=>{
   if(String.IsNullOrWhiteSpace(name.Text)||!Path.IsPathRooted(target.Text)||!Shortcuts.Supported(target.Text)) {MessageBox.Show(this,"Indiquez un nom et un chemin absolu vers un .exe, .lnk, .cmd, .bat ou .ps1.");return;}
   var candidate=new Entry{Id=original==null?Guid.NewGuid().ToString():original.Id,Name=name.Text.Trim(),Target=target.Text.Trim(),Enabled=original==null||original.Enabled,Position=original==null?0:original.Position,Arguments=args.Text,WorkingDirectory=folder.Text,DelayMs=(int)(delay.Value*1000),SkipRunning=skip.Checked,Administrator=admin.Checked,WaitMode=waitMode.SelectedIndex,WaitTimeoutSeconds=(int)waitTimeout.Value};if(candidate.WaitMode!=0){try{if(!Shortcuts.Resolve(candidate).CanDetectRunning)throw new IOException("Pour les scripts, utilisez un délai supplémentaire plutôt qu’une attente du processus.");}catch(Exception ex){MessageBox.Show(this,ex.Message,"Attente du logiciel");return;}}string issue=validate==null?null:validate(candidate);if(issue!=null){MessageBox.Show(this,issue,"Application déjà présente",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}Result=candidate;DialogResult=DialogResult.OK;
  }));buttons.Controls.Add(Theme.Button("Annuler",()=>{DialogResult=DialogResult.Cancel;}));
  if(original!=null){name.Text=original.Name;target.Text=original.Target;args.Text=original.Arguments;folder.Text=original.WorkingDirectory;delay.Value=original.DelayMs/1000m;skip.Checked=original.SkipRunning;admin.Checked=original.Administrator;}else skip.Checked=true;
  Theme.Apply(this);Theme.Primary((Button)buttons.Controls[0]);
 }
 public bool Browse(){using(var d=new OpenFileDialog{Filter="Applications, scripts et raccourcis|*.exe;*.lnk;*.cmd;*.bat;*.ps1|Applications|*.exe|Raccourcis Windows|*.lnk|Scripts Windows|*.cmd;*.bat;*.ps1",CheckFileExists=true,DereferenceLinks=false}){if(d.ShowDialog(this)!=DialogResult.OK)return false;target.Text=d.FileName;if(String.IsNullOrWhiteSpace(name.Text))name.Text=Path.GetFileNameWithoutExtension(d.FileName);folder.Text=Path.GetExtension(d.FileName).Equals(".lnk",StringComparison.OrdinalIgnoreCase)?"":Path.GetDirectoryName(d.FileName);return true;}}
}
public class MainForm : Form {
 CatalogStore store=new CatalogStore();Catalog catalog;Configuration config;bool loading,busy,broken;LaunchLock editorLock;
 DataGridView grid=new DataGridView();FlowLayoutPanel commands=new FlowLayoutPanel();Label info=new Label(),counter=new Label();Button launchButton,shortcutButton;Panel bottom=new Panel();
 Point dragOrigin;int dragRow=-1,dropSlot=-1;string dragId;readonly System.Diagnostics.Stopwatch dragClock=System.Diagnostics.Stopwatch.StartNew();long lastScroll;
 Panel groupArea=new Panel();FlowLayoutPanel tabs=new FlowLayoutPanel(),groupActions=new FlowLayoutPanel();Button newGroupButton,deleteGroupButton;
 Timer statusTimer=new Timer{Interval=2000};bool scanning;int viewRevision;readonly System.Collections.Generic.Dictionary<string,string> launchErrors=new System.Collections.Generic.Dictionary<string,string>();
 string desktopDirectory;string iconDirectory;
 public MainForm(CatalogStore settings=null,string requestedGroup=null,string desktop=null,string iconRoot=null){
  if(settings!=null)store=settings;
  desktopDirectory=desktop??(settings==null?GroupLinks.Desktop:Path.Combine(Path.GetDirectoryName(settings.PathName),"Bureau-test"));iconDirectory=iconRoot??(settings==null?null:Path.Combine(Path.GetDirectoryName(settings.PathName),"icons-test"));
  Text="Panda Launcher";Size=new Size(1120,790);MinimumSize=new Size(1040,720);StartPosition=FormStartPosition.CenterScreen;Padding=new Padding(26,12,26,20);
  var header=new Panel{Dock=DockStyle.Top,Height=132};Controls.Add(header);
  var logo=new PictureBox{Image=Theme.Logo(false),SizeMode=PictureBoxSizeMode.Zoom,Location=new Point(0,9),Size=new Size(104,104)};header.Controls.Add(logo);
  var eyebrow=new Label{Text="VOS APPLICATIONS, À VOTRE RYTHME",AutoSize=true,Location=new Point(120,18)};header.Controls.Add(eyebrow);
  var title=new Label{Text="Panda Launcher",AutoSize=true,Location=new Point(117,42)};header.Controls.Add(title);
  var subtitle=new Label{Text="Déposez vos fichiers ici ; glissez les lignes pour les réordonner.",AutoSize=true,Location=new Point(120,86)};header.Controls.Add(subtitle);
  info.Dock=DockStyle.Bottom;info.Height=58;info.Padding=new Padding(0,12,0,0);Controls.Add(info);
  bottom.Dock=DockStyle.Bottom;bottom.Height=65;bottom.Padding=new Padding(0,12,0,0);Controls.Add(bottom);
  commands.Dock=DockStyle.Top;commands.Height=60;commands.Padding=new Padding(0,10,0,8);
  grid.Dock=DockStyle.Fill;grid.AllowUserToAddRows=false;grid.AllowUserToDeleteRows=false;grid.AllowUserToResizeRows=false;grid.RowHeadersVisible=false;grid.MultiSelect=false;grid.SelectionMode=DataGridViewSelectionMode.FullRowSelect;grid.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill;grid.BackgroundColor=Color.FromArgb(28,31,38);grid.BorderStyle=BorderStyle.None;
  grid.Columns.Add(new DataGridViewCheckBoxColumn{Name="enabled",HeaderText="Actif",FillWeight=16});grid.Columns.Add("name","Logiciel");grid.Columns.Add("target","Chemin");grid.Columns.Add("status","État");grid.Columns[2].FillWeight=180;
  foreach(DataGridViewColumn col in grid.Columns){col.SortMode=DataGridViewColumnSortMode.NotSortable;if(col.Index>0)col.ReadOnly=true;}
  var content=new Panel{Dock=DockStyle.Fill};content.Controls.Add(grid);content.Controls.Add(commands);Controls.Add(content);content.BringToFront();grid.CurrentCellDirtyStateChanged+=(s,e)=>{if(grid.IsCurrentCellDirty)grid.CommitEdit(DataGridViewDataErrorContexts.Commit);};
  groupArea.Dock=DockStyle.Top;groupArea.Height=102;tabs.Dock=DockStyle.Top;tabs.Height=48;tabs.WrapContents=false;groupActions.Dock=DockStyle.Bottom;groupActions.Height=47;groupArea.Controls.Add(tabs);groupArea.Controls.Add(groupActions);content.Controls.Add(groupArea);
  newGroupButton=Theme.Button("＋ Nouveau launcher",NewGroup);groupActions.Controls.Add(newGroupButton);groupActions.Controls.Add(Theme.Button("Paramètres du launcher",()=>ConfigureGroup(false)));deleteGroupButton=Theme.Button("Supprimer ce launcher",DeleteGroup);groupActions.Controls.Add(deleteGroupButton);
  grid.CellValueChanged+=(s,e)=>{if(!loading&&!busy&&!broken&&e.RowIndex>=0&&e.ColumnIndex==0){config.Entries[e.RowIndex].Enabled=(bool)grid.Rows[e.RowIndex].Cells[0].Value;Save();}};
  commands.Controls.Add(Theme.Button("＋ Ajouter",()=>Edit(true)));commands.Controls.Add(Theme.Button("Modifier",()=>Edit(false)));
  commands.Controls.Add(Theme.Button("Supprimer",()=>{int i=Selected();if(i>=0&&MessageBox.Show(this,"Supprimer « "+config.Entries[i].Name+" » de la liste ?","Supprimer",MessageBoxButtons.YesNo)==DialogResult.Yes){config.Entries.RemoveAt(i);Save();RefreshRows();}}));
  commands.Controls.Add(Theme.Button("↑ Monter",()=>MoveEntry(-1)));commands.Controls.Add(Theme.Button("↓ Descendre",()=>MoveEntry(1)));
  counter.AutoSize=true;counter.Margin=new Padding(14,10,0,0);commands.Controls.Add(counter);
  launchButton=Theme.Button("Lancer mes logiciels  →",()=>Launch());launchButton.Dock=DockStyle.Left;launchButton.Width=255;bottom.Controls.Add(launchButton);
  var closeButton=Theme.Button("Fermer les applications",CloseApplications);closeButton.Location=new Point(275,12);closeButton.Size=new Size(215,50);closeButton.Anchor=AnchorStyles.Left|AnchorStyles.Top;bottom.Controls.Add(closeButton);
  shortcutButton=Theme.Button("Créer le raccourci",ApplyShortcut);shortcutButton.Dock=DockStyle.Right;shortcutButton.Width=320;bottom.Controls.Add(shortcutButton);
  Theme.Apply(this);Theme.Primary(launchButton);Theme.Primary(shortcutButton);shortcutButton.BackColor=Color.FromArgb(18,115,104);Theme.Primary((Button)commands.Controls[0]);
  grid.EnableHeadersVisualStyles=false;grid.ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.DisableResizing;grid.ColumnHeadersHeight=42;grid.ColumnHeadersBorderStyle=DataGridViewHeaderBorderStyle.None;grid.CellBorderStyle=DataGridViewCellBorderStyle.SingleHorizontal;grid.GridColor=Theme.Background;grid.BackgroundColor=Theme.Surface;
  grid.ColumnHeadersDefaultCellStyle.BackColor=Theme.Surface;grid.ColumnHeadersDefaultCellStyle.ForeColor=Theme.Muted;grid.ColumnHeadersDefaultCellStyle.Font=new Font("Segoe UI Semibold",9);grid.ColumnHeadersDefaultCellStyle.SelectionBackColor=Theme.Surface;
  grid.DefaultCellStyle.BackColor=Theme.Surface;grid.DefaultCellStyle.ForeColor=Theme.Ink;grid.DefaultCellStyle.SelectionBackColor=Color.FromArgb(232,226,252);grid.DefaultCellStyle.SelectionForeColor=Theme.Ink;grid.DefaultCellStyle.Padding=new Padding(10,6,10,6);grid.RowTemplate.Height=66;grid.Columns[0].MinimumWidth=54;grid.Columns[1].FillWeight=110;grid.Columns[2].FillWeight=185;grid.Columns[3].FillWeight=135;grid.Columns[2].DefaultCellStyle.ForeColor=Theme.Muted;grid.Columns[3].DefaultCellStyle.Font=new Font("Segoe UI",9);
  grid.CellDoubleClick+=(s,e)=>{if(e.RowIndex>=0&&e.ColumnIndex!=0&&!busy&&!broken)Edit(false);};
  SetupDragDrop();
  title.Font=new Font("Segoe UI Semibold",24);eyebrow.Font=new Font("Segoe UI Semibold",9);eyebrow.ForeColor=Theme.Accent;subtitle.ForeColor=Theme.Muted;info.ForeColor=Theme.Muted;counter.ForeColor=Theme.Muted;
  string lockSuffix="";if(settings!=null)using(var sha=System.Security.Cryptography.SHA256.Create())lockSuffix="."+BitConverter.ToString(sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(Path.GetFullPath(settings.PathName).ToUpperInvariant()))).Replace("-","");editorLock=new LaunchLock(@"Local\PandaCoustik.PandaLauncher.Editor.v1"+lockSuffix);
  Shown+=(s,e)=>{if(!editorLock.Acquired){MessageBox.Show(this,"La configuration est déjà ouverte dans une autre fenêtre.");Close();return;}try{catalog=store.Read();if(requestedGroup!=null&&catalog.Groups.Any(g=>g.Id==requestedGroup))catalog.SelectedId=requestedGroup;config=catalog.Selected;if(!File.Exists(store.PathName))store.Save(catalog);RefreshGroups();RefreshRows();}catch(Exception ex){broken=true;commands.Enabled=false;groupArea.Enabled=false;bottom.Enabled=false;grid.Enabled=false;info.Text="Configuration illisible : fichier conservé. Corrigez-le puis relancez l’application.";MessageBox.Show(this,ex.Message,"Configuration protégée");}};
  statusTimer.Tick+=(s,e)=>RefreshRuntimeAsync();statusTimer.Start();Activated+=(s,e)=>{RefreshShortcutButton();RefreshRuntimeAsync();};
  FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};FormClosed+=(s,e)=>{statusTimer.Stop();statusTimer.Dispose();editorLock.Dispose();};
 }
 int Selected(){return grid.SelectedRows.Count==0?-1:grid.SelectedRows[0].Index;}
 void RefreshGroups(){foreach(Control control in tabs.Controls.Cast<Control>().ToArray())control.Dispose();tabs.Controls.Clear();foreach(var group in catalog.Groups){var id=group.Id;var button=Theme.Button(group.Name,()=>{if(busy||broken)return;catalog.SelectedId=id;config=catalog.Selected;Save();RefreshGroups();RefreshRows();});Theme.Apply(button);button.AutoSize=false;button.Size=new Size(185,42);button.Font=new Font("Segoe UI Semibold",10);if(group.Id==catalog.SelectedId)Theme.Primary(button);tabs.Controls.Add(button);}newGroupButton.Enabled=catalog.Groups.Count<5;deleteGroupButton.Enabled=catalog.Groups.Count>1;}
 void NewGroup(){if(busy||broken)return;try{int suffix=1;string name;do{name="Launcher "+suffix++;}while(catalog.Groups.Any(g=>g.Name==name));config=catalog.Add(name);Save();RefreshGroups();RefreshRows();}catch(Exception ex){MessageBox.Show(this,ex.Message);}}
 void ConfigureGroup(bool unused){if(busy||broken)return;try{var group=(Group)config;RefreshShortcutButton();using(var dialog=new GroupDialog(group,GroupLinks.FindClose(group,desktopDirectory),(name,color,enabled,closeName)=>GroupLinks.SavePreferences(store,catalog,group,name,color,enabled,closeName,Application.ExecutablePath,desktopDirectory,iconDirectory))){if(dialog.ShowDialog(this)==DialogResult.OK){RefreshGroups();RefreshRows();info.Text="Options enregistrées. Cliquez sur le bouton des raccourcis pour les appliquer au Bureau.";}}}catch(Exception ex){MessageBox.Show(this,ex.Message,"Paramètres du launcher",MessageBoxButtons.OK,MessageBoxIcon.Information);}}
 void RefreshShortcutButton(){if(config==null||busy||broken||IsDisposed)return;try{var group=(Group)config;var found=GroupLinks.Find(group,desktopDirectory);if(GroupLinks.SynchronizeExternalName(group,found)){store.Save(catalog);RefreshGroups();}bool plural=group.CloseShortcutEnabled??(GroupLinks.FindClose(group,desktopDirectory)!=null);bool exists=found!=null||GroupLinks.FindClose(group,desktopDirectory)!=null;shortcutButton.Text=(exists?"Mettre à jour ":"Créer ")+(plural?"les raccourcis":"le raccourci");shortcutButton.Enabled=true;}catch(Exception ex){shortcutButton.Text="Vérifier le raccourci";info.Text=ex.Message;}}
 void ApplyShortcut(){if(busy||broken||config==null)return;try{var group=(Group)config;bool closing=group.CloseShortcutEnabled??(GroupLinks.FindClose(group,desktopDirectory)!=null);GroupLinks.SavePreferences(store,catalog,group,group.Name,group.Icon,closing,group.CloseShortcutName??GroupLinks.DefaultCloseName(group.Name),Application.ExecutablePath,desktopDirectory,iconDirectory,true);RefreshShortcutButton();info.Text=closing?"Les deux raccourcis sont à jour sur le Bureau.":"Raccourci de lancement à jour ; raccourci de fermeture retiré si présent.";}catch(Exception ex){MessageBox.Show(this,ex.Message,"Raccourci du launcher",MessageBoxButtons.OK,MessageBoxIcon.Information);}}
 async void RefreshRuntimeAsync(){if(scanning||busy||broken||config==null||IsDisposed||!Visible)return;scanning=true;int revision=viewRevision;var entries=config.Entries.ToArray();try{var states=await System.Threading.Tasks.Task.Run(()=>entries.ToDictionary(e=>e.Id,e=>RuntimeProbe.Read(e)));if(IsDisposed||busy||broken||revision!=viewRevision)return;for(int i=0;i<config.Entries.Count;i++){var entry=config.Entries[i];RuntimeState state;if(!states.TryGetValue(entry.Id,out state))continue;string issue;bool hasError=launchErrors.TryGetValue(entry.Id,out issue);string label=state.Text+(entry.Enabled?"":" · désactivé dans ce launcher")+(hasError?" · "+issue:"");grid.Rows[i].Cells[3].Value=label;grid.Rows[i].Cells[3].ToolTipText=label;grid.Rows[i].Cells[3].Style.ForeColor=hasError||state.Kind==RuntimeKind.Error?Color.FromArgb(182,48,65):state.Kind==RuntimeKind.Running?Color.FromArgb(25,123,91):Theme.Muted;}}catch(Exception ex){if(!IsDisposed)Journal.Write("Actualisation des états : "+ex.Message);}finally{scanning=false;}}
 void DeleteGroup(){if(busy||broken||catalog.Groups.Count<=1)return;var group=(Group)config;try{GroupLinks.Find(group,desktopDirectory);if(MessageBox.Show(this,"Supprimer le launcher « "+group.Name+" », sa liste et ses raccourcis Bureau associés ? Les logiciels restent installés.","Supprimer le launcher",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;GroupLinks.Delete(store,catalog,group,desktopDirectory);config=catalog.Selected;RefreshGroups();RefreshRows();}catch(Exception ex){MessageBox.Show(this,ex.Message);}}
 bool Save(){try{store.Save(catalog);counter.Text=config.Entries.Count(e=>e.Enabled)+" actif(s) / "+config.Entries.Count;return true;}catch(Exception ex){broken=true;commands.Enabled=false;groupArea.Enabled=false;bottom.Enabled=false;grid.Enabled=false;MessageBox.Show(this,"Enregistrement impossible. Les modifications en mémoire ne sont pas sauvegardées.\n"+ex.Message);return false;}}
 void RefreshRows(){viewRevision++;loading=true;grid.Rows.Clear();foreach(var e in config.Entries){int i=grid.Rows.Add(e.Enabled,e.Name,e.Target,e.Enabled?"●  En attente":"○  Désactivé");grid.Rows[i].Cells[3].Style.ForeColor=e.Enabled?Color.FromArgb(68,93,145):Theme.Muted;}loading=false;counter.Text=config.Entries.Count(e=>e.Enabled)+" actif(s) / "+config.Entries.Count;info.Text=config.Entries.Count==0?"Votre liste est vide. Cliquez sur Ajouter pour préparer votre premier décollage.":"États actualisés toutes les 2 secondes · Processus détectés, disponibilité non garantie.";RefreshShortcutButton();RefreshRuntimeAsync();}
 string ValidateEntry(Entry candidate){var duplicate=Entries.FindDuplicate(config.Entries,candidate);return duplicate==null?null:"Cette application est déjà dans la liste : « "+duplicate.Name+" »"+(duplicate.Enabled?".":" (désactivée).")+"\n\nModifiez l’entrée existante au lieu de l’ajouter une seconde fois.";}
 void Edit(bool add){int i=Selected();if(!add&&i<0)return;using(var d=new Editor(add?null:config.Entries[i],ValidateEntry)){if(add&&!d.Browse())return;if(d.ShowDialog(this)==DialogResult.OK){if(add)config.Entries.Add(d.Result);else config.Entries[i]=d.Result;Save();RefreshRows();}}}
 void SetupDragDrop(){
  grid.AllowDrop=true;
  grid.MouseDown+=(s,e)=>{var hit=grid.HitTest(e.X,e.Y);dragOrigin=e.Location;dragRow=e.Button==MouseButtons.Left&&hit.RowIndex>=0&&hit.ColumnIndex>0&&!busy&&!broken?hit.RowIndex:-1;};
  grid.MouseUp+=(s,e)=>dragRow=-1;
  grid.MouseMove+=(s,e)=>{if(e.Button!=MouseButtons.Left||dragRow<0||busy||broken||dragId!=null)return;var size=SystemInformation.DragSize;if(new Rectangle(dragOrigin.X-size.Width/2,dragOrigin.Y-size.Height/2,size.Width,size.Height).Contains(e.Location))return;dragId=config.Entries[dragRow].Id;try{grid.DoDragDrop(dragId,DragDropEffects.Move);}finally{dragId=null;dragRow=-1;dropSlot=-1;grid.Invalidate();}};
  grid.DragEnter+=(s,e)=>e.Effect=ValidFiles(e)?DragDropEffects.Copy:ValidDrag(e)?DragDropEffects.Move:DragDropEffects.None;
  grid.DragOver+=(s,e)=>{if(ValidFiles(e)){e.Effect=DragDropEffects.Copy;dropSlot=-1;grid.Invalidate();return;}if(!ValidDrag(e)){e.Effect=DragDropEffects.None;return;}e.Effect=DragDropEffects.Move;var p=grid.PointToClient(new Point(e.X,e.Y));if(dragClock.ElapsedMilliseconds-lastScroll>140&&grid.RowCount>0){int first=grid.FirstDisplayedScrollingRowIndex;if(first>=0){if(p.Y<grid.ColumnHeadersHeight+22&&first>0)grid.FirstDisplayedScrollingRowIndex=first-1;else if(p.Y>grid.ClientSize.Height-24&&first<grid.RowCount-1)grid.FirstDisplayedScrollingRowIndex=first+1;}lastScroll=dragClock.ElapsedMilliseconds;}dropSlot=SlotAt(p);grid.Invalidate();};
  grid.DragLeave+=(s,e)=>{dropSlot=-1;grid.Invalidate();};
  grid.DragDrop+=HandleDrop;
  grid.Paint+=(s,e)=>{if(dropSlot<0||grid.RowCount==0)return;int row=Math.Min(dropSlot,grid.RowCount-1);var bounds=grid.GetRowDisplayRectangle(row,false);int y=dropSlot==grid.RowCount?bounds.Bottom-2:bounds.Top;if(y<grid.ColumnHeadersHeight||y>grid.ClientSize.Height)return;using(var pen=new Pen(Theme.Accent,3))e.Graphics.DrawLine(pen,3,y,grid.ClientSize.Width-5,y);};
 }
 bool ValidDrag(DragEventArgs e){return !busy&&!broken&&dragId!=null&&e.Data!=null&&e.Data.GetDataPresent(typeof(string))&&String.Equals(e.Data.GetData(typeof(string)) as string,dragId,StringComparison.Ordinal);}
 bool ValidFiles(DragEventArgs e){return !busy&&!broken&&config!=null&&e.Data!=null&&e.Data.GetDataPresent(DataFormats.FileDrop);}
 void AddDroppedFiles(string[] files){var batch=DropBatch.Prepare(files,config.Entries);using(var dialog=new Form{Text="Ajouter les programmes déposés",Size=new Size(690,430),StartPosition=FormStartPosition.CenterParent,Padding=new Padding(16)}){var list=new ListBox{Dock=DockStyle.Fill,HorizontalScrollbar=true};foreach(var entry in batch.Added)list.Items.Add("Ajouter : "+entry.Name+" — "+entry.Target);foreach(string issue in batch.Issues)list.Items.Add("Ignoré : "+issue);dialog.Controls.Add(list);var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=50};var confirm=Theme.Button("Ajouter "+batch.Added.Count+" programme(s)",()=>dialog.DialogResult=DialogResult.OK);confirm.Enabled=batch.Added.Count>0;actions.Controls.Add(confirm);actions.Controls.Add(Theme.Button("Annuler",()=>dialog.DialogResult=DialogResult.Cancel));dialog.Controls.Add(actions);Theme.Apply(dialog);Theme.Primary(confirm);if(dialog.ShowDialog(this)==DialogResult.OK){config.Entries.AddRange(batch.Added);Save();RefreshRows();info.Text=batch.Added.Count+" programme(s) ajouté(s).";}}}
 public static bool ConfirmElevation(IWin32Window owner,Entry entry){return MessageBox.Show(owner,"La fermeture de « "+entry.Name+" » nécessite des droits administrateur.\n\nPanda Launcher va demander à Windows l’autorisation de fermer ce logiciel. La fenêtre Windows peut afficher « Éditeur inconnu », car Panda Launcher n’est pas signé.\n\nCliquez sur OK pour afficher cette demande, ou sur Annuler pour laisser le logiciel ouvert.","Autoriser la fermeture de "+entry.Name,MessageBoxButtons.OKCancel,MessageBoxIcon.Information)==DialogResult.OK;}
 public static bool ConfirmForce(IWin32Window owner,Entry entry){return MessageBox.Show(owner,"« "+entry.Name+" » est toujours actif. Forcer l'arrêt de ses processus ?\n\nLes données non enregistrées et les enregistrements en cours peuvent être perdus. Choisissez Non pour le laisser ouvert.","Fermeture forcée",MessageBoxButtons.YesNo,MessageBoxIcon.Warning,MessageBoxDefaultButton.Button2)==DialogResult.Yes;}
 async void CloseApplications(){if(busy||broken||config==null)return;using(var gate=new LaunchLock(Launcher.LockName)){if(!gate.Acquired){MessageBox.Show(this,"Une opération est déjà en cours.");return;}busy=true;viewRevision++;launchErrors.Clear();commands.Enabled=false;groupArea.Enabled=false;bottom.Enabled=false;grid.Enabled=false;try{int errors=await AppCloser.Close(config,(entry,state,error)=>{int i=config.Entries.FindIndex(x=>x.Id==entry.Id);grid.Rows[i].Cells[3].Value=state;grid.Rows[i].Cells[3].ToolTipText=state;if(error)launchErrors[entry.Id]=state;else launchErrors.Remove(entry.Id);info.Text=entry.Name+" : "+state;},entry=>ConfirmForce(this,entry),8000,entry=>ConfirmElevation(this,entry));info.Text=errors==0?"Fermeture du launcher terminée.":"Certains logiciels restent ouverts : consultez leurs confirmations ou les états.";}catch(Exception ex){MessageBox.Show(this,ex.Message);}finally{busy=false;commands.Enabled=!broken;groupArea.Enabled=!broken;bottom.Enabled=!broken;grid.Enabled=!broken;RefreshRuntimeAsync();}}}
 int SlotAt(Point p){for(int i=0;i<grid.RowCount;i++){var r=grid.GetRowDisplayRectangle(i,false);if(r.Height<=0)continue;if(p.Y<r.Top+r.Height/2)return i;}return grid.RowCount;}
 void HandleDrop(object sender,DragEventArgs e){if(ValidFiles(e)){AddDroppedFiles((string[])e.Data.GetData(DataFormats.FileDrop));return;}if(!ValidDrag(e))return;int slot=SlotAt(grid.PointToClient(new Point(e.X,e.Y)));int moved=Entries.MoveToSlot(config,dragId,slot);dropSlot=-1;if(moved<0)return;Save();RefreshRows();grid.ClearSelection();grid.Rows[moved].Selected=true;grid.CurrentCell=grid.Rows[moved].Cells[1];info.Text="Ordre de lancement enregistré.";}
 void MoveEntry(int direction){int i=Selected(),j=i+direction;if(i<0||j<0||j>=config.Entries.Count)return;var e=config.Entries[i];config.Entries.RemoveAt(i);config.Entries.Insert(j,e);Save();RefreshRows();grid.ClearSelection();grid.Rows[j].Selected=true;}
 async void Launch(){using(var gate=new LaunchLock(Launcher.LockName)){if(!gate.Acquired){MessageBox.Show(this,"Une séquence de lancement est déjà en cours.");return;}busy=true;launchErrors.Clear();commands.Enabled=false;groupArea.Enabled=false;bottom.Enabled=false;grid.Enabled=false;launchButton.Text="Lancement en cours…";try{catalog=store.Read();config=catalog.Selected;if(!File.Exists(store.PathName))store.Save(catalog);RefreshGroups();RefreshRows();int n=await Launcher.Run(config,(entry,state,error)=>{int i=config.Entries.FindIndex(x=>x.Id==entry.Id);if(error)launchErrors[entry.Id]=state;else launchErrors.Remove(entry.Id);grid.Rows[i].Cells[3].Value=state;grid.Rows[i].Cells[3].Style.ForeColor=error?Color.FromArgb(182,48,65):Color.FromArgb(25,123,91);grid.Rows[i].Cells[3].ToolTipText=state;info.Text=entry.Name+" : "+state;});info.Text=n==0?"Séquence terminée. Demandes envoyées à Windows ; la disponibilité des logiciels n’est pas vérifiée.":n+" erreur(s). Survolez les états pour lire le détail.";}catch(Exception ex){MessageBox.Show(this,ex.Message);}finally{busy=false;commands.Enabled=!broken;groupArea.Enabled=!broken;bottom.Enabled=!broken;grid.Enabled=!broken;launchButton.Text="Lancer mes logiciels  →";RefreshRuntimeAsync();}}}
}
public class ProgressForm : Form {
 ListBox messages=new ListBox{Dock=DockStyle.Fill,HorizontalScrollbar=true};bool busy=true;Button edit;bool closing;string groupId;PictureBox logo;Label title;
 public ProgressForm(string requestedGroup=null,bool close=false){closing=close;groupId=requestedGroup;Text="Panda Launcher";Size=new Size(740,390);Padding=new Padding(22);StartPosition=FormStartPosition.CenterScreen;Controls.Add(messages);var header=new Panel{Dock=DockStyle.Top,Height=100};logo=new PictureBox{Image=Theme.Logo(true),SizeMode=PictureBoxSizeMode.Zoom,Size=new Size(90,90),Dock=DockStyle.Left};header.Controls.Add(logo);title=new Label{Text=closing?"Fermeture du launcher":"Lancement du launcher",AutoSize=true,Location=new Point(104,24)};header.Controls.Add(title);Controls.Add(header);edit=Theme.Button("Ouvrir la configuration",()=>{System.Diagnostics.Process.Start(Application.ExecutablePath,groupId==null?"":"--group "+groupId);Close();});edit.Dock=DockStyle.Bottom;edit.Height=45;edit.Visible=false;Controls.Add(edit);Theme.Apply(this);title.Font=new Font("Segoe UI Semibold",19);messages.BorderStyle=BorderStyle.None;messages.ItemHeight=28;messages.BackColor=Theme.Surface;Theme.Primary(edit);Shown+=(s,e)=>Run();FormClosing+=(s,e)=>{if(busy)e.Cancel=true;};}
 async void Run(){using(var gate=new LaunchLock(Launcher.LockName)){if(!gate.Acquired){busy=false;MessageBox.Show(this,"Une séquence de lancement est déjà en cours.");Close();return;}int errors=0;try{var store=new CatalogStore();var catalog=store.Read();if(!File.Exists(store.PathName))store.Save(catalog);var c=catalog.ForLaunch(groupId);groupId=c.Id;title.Text=c.Name;Text="Panda Launcher — "+c.Name;logo.Image=Theme.RunLogo(c.Icon);if(closing)errors=await AppCloser.Close(c,(e,state,err)=>messages.Items.Add(e.Name+" — "+state),e=>MainForm.ConfirmForce(this,e),8000,e=>MainForm.ConfirmElevation(this,e));else if(!c.Entries.Any(x=>x.Enabled)){messages.Items.Add("Aucun logiciel activé dans ce launcher. Ouvrez la configuration.");errors++;}else errors=await Launcher.Run(c,(e,state,err)=>messages.Items.Add(e.Name+" — "+state));}catch(Exception ex){errors++;messages.Items.Add(ex.Message);Journal.Write(ex.Message);}busy=false;if(errors==0)Close();else edit.Visible=true;}}
}
public static class Program {
 public static string GroupArgument(string[] args){if(args.Count(x=>x=="--group")>1||args.Contains("--launch")&&args.Contains("--close"))throw new IOException("Arguments de raccourci contradictoires.");int index=Array.IndexOf(args,"--group");if(index<0)return null;Guid id;if(index+1>=args.Length||!Guid.TryParseExact(args[index+1],"D",out id))throw new IOException("Identifiant de launcher invalide dans le raccourci.");return id.ToString("D");}
 [STAThread] public static void Main(string[] args){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);try{if(args.Length>0&&args[0]=="--process-action"){try{if(args.Length!=5||(args[3]!="force"&&args[3]!="close"))throw new IOException("Action invalide.");bool acted=AppCloser.ActOnProcess(int.Parse(args[1]),long.Parse(args[2]),System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(args[4])),args[3]=="force");Environment.ExitCode=acted?0:1;}catch{Environment.ExitCode=1;}return;}string group=GroupArgument(args);Application.Run(args.Contains("--launch")||args.Contains("--close")?(Form)new ProgressForm(group,args.Contains("--close")):new MainForm(null,group));}catch(Exception ex){MessageBox.Show(ex.Message,"Panda Launcher",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
}
}










